### ISSUE TITLE
Software Requirements Specification Structure Enhancement

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#10]
Continuing #9, I'd like to collect enhancements for the structure of our Software Requirement Specifications Document.

As a starting point, I will use the structure given in the [SWT lecture example requirements specification](https://ilias.studium.kit.edu/ilias.php?ref_id=435203&cmd=sendfile&cmdClass=ilrepositorygui&cmdNode=ed&baseClass=ilRepositoryGUI).

Please post any enhancements and modifications of this structure you can already name. There will of course be possibilities to adjust the structure at later points.

**Comment by m1cm1c** [comment]
"non-functional requirement" is an umbrella term. It should be splitted into several more precise categories.

**Comment by jGleitz** [comment]
@m1cm1c: Definitely. I'll adopt that.

@RomanLangrehr: I agree that the table is quite meaningless. The book describes a way to specify ranges for requirements of requirements. One could start with it and further make the values verifiable. I would then go ahead and annotate importance and quality requirements for each requirement. Does that solve the issue for you?

**Comment by m1cm1c** [comment]
Is there a section documenting which software our software depends on?

**Comment by jGleitz** [comment]
> Is there a section documenting which software our software depends on?

That would be “software environment”, wouldn’t it?

**Comment by m1cm1c** [comment]
I only see "product environment" in the lecture. Do you mean this one?

If so, here is a screenshot of the slide regarding its contents:

![](http://i.imgur.com/PJiI3zW.png?1)

It's up to speculation whether it's supposed to be in 3.1 or not.

**Comment by RomanLangrehr** [comment]
@jGleitz 
> I agree that the table is quite meaningless. The book describes a way to specify ranges for requirements of requirements (at the bottom of p. 493). One could start with it and further make the values verifiable. I would then go ahead and annotate importance and quality requirements for each requirement. Does that solve the issue for you?

That sounds great.

**Comment by m1cm1c** [comment]
If you think that it fits in 3.1, I'm okay with that, btw. I just want the dependencies to be in there.

**Comment by jGleitz** [comment]
@m1cm1c: Yep, 3.1 is exactly what I mean (didn’t look up the exact term before commenting)

**Comment by jGleitz** [comment]
> It's up to speculation whether it's supposed to be in 3.1 or not.

Like most things in that part of the lecture… :(

**Comment by m1cm1c** [comment]
Maybe we should ask this tomorrow. 

On November 20, 2015 12:36:12 AM GMT+01:00, Joshua Gleitze <notifications@github.com> wrote:
>> It's up to speculation whether it's supposed to be in 3.1 or not.
>
>Like most things in that part of the lecture… :(
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/issues/10#issuecomment-158234431

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jGleitz** [comment]
> Maybe we should ask this tomorrow.

I don’t think they now stuff like that…

**Comment by flyfl** [comment]
First, I think it might be better to evaluate what our SRS should contain using the given structure. If we then realize that any part becomes too extensive, we can adjust that immediately. But for now I can't predict any useful format modifications.

**Comment by jGleitz** [comment]
> But for now I can't predict any useful format modifications.

I totally agree. Further discussions on the SRS shall be done on #18 and following Pull Requests or Issues.
