### ISSUE TITLE
Invalid BiBTeX-entries: conwaysLaw, tuChemPcm

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#107]
This entry is invalid, as it doesn't provide enough information (Title, Author, etc are always required).

And when citing websites: _Always write down, when you visited the website and make a local copy!_
We can discuss, if it would be a good idea to put these local copys in our repo.

**Comment by RomanLangrehr** [comment]
An author is missing in tuChemPcm, too!

**Comment by jGleitz** [comment]
```
Warning--entry type for "tuChemPcm" isn't style-file defined
--line 124 of file Bibliography.bib

Warning--entry type for "conwaysLaw" isn't style-file defined
--line 131 of file Bibliography.bib

Warning--to sort, need author or key in tuChemPcm

Warning--to sort, need author or key in conwaysLaw

Warning--empty year in conwaysLaw
```
