### ISSUE TITLE
Specifiy Adaptive Timeout

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#113]
Adaptive timemout must be added to the requirements specification.

**Comment by jGleitz** [comment]
It is added but needs to be specified.

**Comment by m1cm1c** [comment]
Please contribute if you can think of other factors on which the adaptive timeout can depend.

**Comment by m1cm1c** [comment]
We're talking about time until termination, aren't we?

**Comment by jGleitz** [comment]
> We're talking about time until termination, aren't we?

I’d say the time until a specific measurement is aborted.

Does the momentary definition in the SRS lack anything?

**Comment by jGleitz** [comment]
@m1cm1c: Why is this stil open?

**Comment by m1cm1c** [comment]
It seems like I forgot the "fixes #113" when creating the pull request.
