### ISSUE TITLE
Is `/F50/` non-functional?

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#122]

**Comment by flyfl** [comment]
"Beagle does not modify the provided source code files."
I also think it is not functional, but I am not sure, if non-functinal would fit better.

**Comment by viridispirus** [comment]
I agree, to @flyfl this is something we can check. So it might be non-functional.

**Comment by jGleitz** [comment]
Didn’t we talk about that in the last meeting? What was the result?

**Comment by m1cm1c** [comment]
Yes, we did. The result has been that it's not functional.

But note that it already has been moved around. The current /F50/ was previously non-functional and has been changed to functional. So this issue can be closed.
