### ISSUE TITLE
Sort `Reference notation`

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#123]
I'd prefer `Reference notation` to be sorted alphabetically.

**Comment by RomanLangrehr** [comment]
If we sort it alphabetically, I think we should keep /X##/ and /OX##/ together. So after /F##/, there should be /OF##/, although that is not the alphebtic order.

**Comment by jGleitz** [comment]
The is no `/O*#/` anymore, we removed it in favour of 

> A preceding “O” marks optional points. These relate to features that are desired and planned, but can not surely be implemented in the project's scope. They also serve as an outlook for further development.

**Comment by RomanLangrehr** [comment]
> The is no /O*#/ anymore, we removed it in favour of

Oh sorry. Than forget about it.

**Comment by acBerger** [comment]
I agree with sorting alphabetically as it is easier for others to read.
