### ISSUE TITLE
Is /OQ40/ functional?

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#128]
I think /OQ40/:  Beagle stops measruements by an adaptive timeout. is rather a functional than a non-functional requirement.

**Comment by flyfl** [comment]
Agreed

**Comment by m1cm1c** [comment]
It doesn't add a function but only changes one. But we should ask this tomorrow.

**Comment by m1cm1c** [comment]
I added it to the agenda.

**Comment by jGleitz** [comment]
> It doesn't add a function but only changes one.

Doesn’t matter. That’s actually true for many functional requirements.

I think that’s functional, too.
