### ISSUE TITLE
File Name Format

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#13]
Let’s define a file name format that we’ll stick to throughout the project (although exceptions will be made for source code). Currently, we use at least **3** different formats, and I hate the chaos. 

I propose (for both files and folders):

 * only lowercase
 * use spaces to separate words
 * specific is more important than short
 * avoid deep nesting of folders

What do you think?

**Comment by m1cm1c** [comment]
Why the lowercase restriction? I don't see how this is an improvement over using capitalization.

**Comment by RomanLangrehr** [comment]
> Why the lowercase restriction? I don't see how this is an improvement over using capitalization.

I agree, that capital letters are not a bad thing in filenames.
All other restrictions are usefull.

**Comment by jGleitz** [comment]
> Why the lowercase restriction?

1. We need to agree on something
2. English is an all lowercase language (with the exception of personal names). Capitalization makes file names look like headlines, which I find odd.

**Comment by m1cm1c** [comment]
But many files are named liked head lines. The name of a file often is the title of the document stored in the file – the headline of which of course is written like headlines are written in English.

**Comment by jGleitz** [comment]
Well, do whatever you like, but **please** be consistent.

**Comment by jGleitz** [comment]
Another argument: All Java source folders will be lowercase ;)

**Comment by RomanLangrehr** [comment]
> All Java source folders will be lowercase ;)

But the java source files will contain uppercase letters.

**Comment by m1cm1c** [comment]
To defend @jGleitz: He wrote:
> although exceptions will be made for source code

But I still think we should name our files like it's done in headlines and titles.

**Comment by jGleitz** [comment]
> But I still think we should name our files like it's done in headlines and titles.

If you insist… it still looks _really really_ odd to me.

 But if the both of you agree on that, I’m overruled.

**Comment by flyfl** [comment]
Consistency, yes. But I'm abstaining which variant we choose.

**Comment by jGleitz** [comment]
So to make a conclusion: How exactly will we write our file names? 

1. folders in English Heading Style, files lowercase
2. folders lowercase, files in English Heading Style
3. files and folders in English Heading Style

**Comment by RomanLangrehr** [comment]
In my opinion point 3 is the best solution, but we should make an exception for the eclipse project. This should have the common foler names.

**Comment by m1cm1c** [comment]
My opinion: Java convention for code files (and folders, like it's done for packages); English heading style for everything else.

**Comment by jGleitz** [comment]
@m1cm1c: Just to be sure: That’s exactly what @RomanLangrehr said, isn’t it?

**Comment by RomanLangrehr** [comment]
Yes it is..

**Comment by jGleitz** [comment]
Okay. So we decide for

> Java convention for code files (and folders, like it's done for packages); English heading style for everything else.

with one vote against, two votes in favour and three abstentions.
