### ISSUE TITLE
Saving test results

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#135]
In out meeting yesterday we decided to write our data in the given PCM. If we do so, existing measurement data could be deleted. Some time before we talked about (maybe even decided) we want give the ability to do several measurements and compare them. 
- if the user wants to compare his previous software to the improved this may not even be a problem, as we would need both PCMs (if he does not save the older one it is his fault).
- if the user however wants to measure the exact same software (same version) twice and compare he has to copy the PCM at the moment. This can be a proper way to do.

We have to decide if we want to have a viewing for comparing and if we do, how this works.

So probably this is not even a problem at all.

**Comment by jGleitz** [comment]
Simply overriding could also be a problem when the user wants to retest to gain more precision.

**Comment by jGleitz** [comment]
For now, we ignore this.
