### ISSUE TITLE
/OF110/ What do we mean by “The user may specify the parametrisation of a component”

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#141]
It’s unspecific and I’m not sure how to understand it.

**Comment by acBerger** [comment]
It may be helpful to tell us where you got this from.

**Comment by jGleitz** [comment]
That’s `/OF110/` in the moment.

**Comment by flyfl** [comment]
Maybe it should implicate, that a user can modify the PCM annotations on its own?

**Comment by jGleitz** [comment]
> Maybe it should implicate, that a user can modify the PCM annotations on its own?

But that’s a functionality Palladio offers.

**Comment by acBerger** [comment]
I have no idea.
We said that it is possible to measure one (or more) component(s) and not only the whole system. And we also said that there should be "parameters" the user can set (timeout etc.).
Maybe the person who wrote this tries to put these things together.

This is the best explanation I can think of at the moment, even through it does not seem to be very realistic.
