### ISSUE TITLE
SRS: Make everything referenceable

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#15]
I just quickly want to put up a decision for disucssion:

I decided to make *everything* in our SRS referenceable. That includes criteria stated in the first section, environment attributes, and of course requirements and test cases.

I just figured it made sense, as it enables us to cross-reference everything. (Like stating that a requirement adopts a certain criterion, or stating that a non functional requirement is enforced by an environment attribute).

Neither the lecture nor the book does that.

Do you agree with me or do you think it isn’t useful?

**Comment by m1cm1c** [comment]
I agree. That's useful.

**Comment by RomanLangrehr** [comment]
I agree, too.

**Comment by flyfl** [comment]
Agreed

**Comment by jGleitz** [comment]
That’s positive.
