### ISSUE TITLE
Examine if all mandatory defined tasks are realistic

### ISSUE THREAD

**Issue by flyfl** [Beagle-PSE/Beagle#152]
The SRS defines a contract for us developers to fulfil all of the mandatory tasks/functions/... we mentioned in it. We may not want to have the overwhelming burden, to do the design or implement the source code for functions, that lead to enormous investigation or unsatisfying results.
Please review the SRS for any "mandatory"-signed points, that may open Pandora's Box.

**Comment by RomanLangrehr** [comment]
Result:

* /D100/ When we only annotate the CPU resource demand, we have to distinguish between CPU usage and I/O usage. I think we should only specify, that we annotate a "total usage" resource demand.
 * /F230/ We can't measure all components, so I think we have to express this different.
 * /Q10/ we probably need SoMoX

**Comment by jGleitz** [comment]
> /D100/ When we only annotate the CPU resource demand, we have to distinguish between CPU usage and I/O usage. I think we should only specify, that we annotate a "total usage" resource demand.

As far as I know, the CTA is capable of only returning true CPU time. Approaches like byte counter do have a problem with this at all. I figure this will not be a problem.

> /F230/ We can't measure all components, so I think we have to express this different.

Correct. I adapted that somewhere, I think in #236. (I know that’s bad). Please sse if it’s fixed for you.

> /Q10/ we probably need SoMoX

I don’t think so. Why should that be the case?

**Comment by RomanLangrehr** [comment]
> I don’t think so. Why should that be the case?

We probably don't need SoMoX. But should we mention JaMoPP here? or is this not a seperate program, but rather a libary?

**Comment by RomanLangrehr** [comment]
> Correct. I adapted that somewhere, I think in #236. (I know that’s bad). Please sse if it’s fixed for you.

Is fixed.

**Comment by jGleitz** [comment]
> Or is this not a separate program, but rather a libary?

Yeah, I think so. We don’t mention that we’ll be using JUnit, do we?

**Comment by RomanLangrehr** [comment]
> Yeah, I think so. We don’t mention that we’ll be using JUnit, do we?
No
