### ISSUE TITLE
Purpose and Goals Improvements

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#155]
### 1.1 Criteria

- /P10/  can easily be misunderstood, either change "analyse" to a better fitting word or try to make clear what we mean in an other way.

- /P30/ this can be followed from /P10/ and /P20/. Expand these points to include /P30/.

### 1.2 Boundary
 - /B40/  As Beagle could be used with other languages than Java if it is implemented for this, this point should be deleted.

**Comment by m1cm1c** [comment]
I moved `Add more points to optional criteria` to #162 so this issue can be closed.

**Comment by RomanLangrehr** [comment]
Joining with #153 

> * More bullet points
* Move use case diagram here
