### ISSUE TITLE
Application Improvements

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#156]
### 2.1 Application Field
- specify "execute" Somox in Diagram

- /A30/ this is missing concepts (take them from Disertation or CSE Paper) -> what is Beagle used for?

### 2.2 Target Group
Point out that software architects (in a classic way) probably won't use Beagle, (even through there are some who do).

**Comment by flyfl** [comment]
I have not started at all to deal with this issue yet. I'm distracted of so much little things that occur during work flow and now my SmartGit will do nothing because of this little ":" sign. I'd be pleased if someone else could try to fix this issue.

**Comment by jGleitz** [comment]
@flyfl: Copy all changes that are not on your GitHub fork to some folder. Remove the whole repo and freshly clone it with SmartGit. Should fix it for you.

**Comment by flyfl** [comment]
That's what I've done. Also with the forked origin repo.
