### ISSUE TITLE
Users

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#168]
We often used phrases like "The user ..., he ..."
As we decided to use the plural form, this has to be changed for the whole document.

**Comment by m1cm1c** [comment]
Why don't you want to use the singular they?

**Comment by jGleitz** [comment]
@m1cm1c because we don’t want to.

**Comment by m1cm1c** [comment]
We usually talk about what 1 user does. If something is done typically, we can use plural. But always talking about users in plural is just awful.

**Comment by flyfl** [comment]
I agree with @m1cm1c. I don't think this must be done with each 3rd personal pronoun. In some cases that may look more "elegant" and we can do this. I dislike such avoidance strategies, that require to change (actual correct) practicing one is used to.
