### ISSUE TITLE
Translation needed

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#17]
If have a hard time translating the following points:

II PRODUKTEINSATZ
II.1. Anwendungsbereiche
II.2 Zielgruppen
II.3 Betriebsbedingungen

Could somebody please help?

**Comment by m1cm1c** [comment]
Product Application
Scope
Target Groups
Operating Conditions

**Comment by jGleitz** [comment]
That’s exactly what I thought. But:

 * I tried not to use “product” in any heading, as it seemed overly generic.
 * “scope” means something different in the IEEE standard.

**Comment by jGleitz** [comment]
I adopted:

2 Application
2.1 Application Field
2.2 Target Group
2.3 Operation Conditions
