### ISSUE TITLE
Revise Application

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#195]

**Comment by acBerger** [comment]
Please be aware that #156  has to be finished before.

**Comment by m1cm1c** [comment]
Fixed by #210.

**Comment by jGleitz** [comment]
> Fixed by #210.

As #156 is not closed, this can not possibly be true.

**Comment by m1cm1c** [comment]
Oops, sorry.

**Comment by m1cm1c** [comment]
But now it's unblocked, isn't it?

**Comment by jGleitz** [comment]
Yep

**Comment by jGleitz** [comment]
Is the chapter revised?

**Comment by m1cm1c** [comment]
I revised it but there was a change afterwards for which it had been reserved. I have no idea how extensive this change was.

**Comment by jGleitz** [comment]
>  I have no idea how extensive this change was. 

Revision-worthy, I guess.

**Comment by m1cm1c** [comment]
But they probably already checked the current version out.

**Comment by jGleitz** [comment]
> But they probably already checked the current version out.

Yeah. But our SRS will be useful and continued throughout development. So fixing errors in it is still wise.

**Comment by m1cm1c** [comment]
Okay.

**Comment by m1cm1c** [comment]
There probably one were small changes. I couldn't find anything except missing blanks. The PR is available (#195).
