### ISSUE TITLE
Revise Data

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#197]

**Comment by m1cm1c** [comment]
@jGleitz I assigned you to this one because the chapter contains the term "the software" awfully often.

**Comment by acBerger** [comment]
I went through the Data section and I think it is good.

"The software" is correct for all occurrences here. ("a software" would not be okay)

**Comment by jGleitz** [comment]
I think is right. From my point of view you can use “the software” just like you could use “the money” here.

**Comment by jGleitz** [comment]
@acBerger is this chapter completly revised?
