### ISSUE TITLE
Revise Test Cases

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#200]

**Comment by acBerger** [comment]
blocked by #183

**Comment by acBerger** [comment]
As I wrote most of this chapter I should not be the one to revise this.

**Comment by m1cm1c** [comment]
When will this be unblocked? We still have to revise several chapters.

**Comment by acBerger** [comment]
#183  has to be done before. As soon as it is done, this can be unblocked.

**Comment by jGleitz** [comment]
@m1cm1c I’ll do #183 after I finished #121. Sorry for the delay!
