### ISSUE TITLE
Revise Models

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#202]

**Comment by m1cm1c** [comment]
I created these revise issues so only one person works on a specific file at a time because two people revising the same file simultaneously will result in a lot of merge conflicts.

**Comment by jGleitz** [comment]
this is obviously blocked by #88

**Comment by viridispirus** [comment]
Revise this chapter and lgtm.

**Comment by flyfl** [comment]
> systemsoftware architecturearchitecture

**Comment by acBerger** [comment]
> systemsoftware architecturearchitecture

@flyfl What should that tell us?

**Comment by flyfl** [comment]
Mistakes within the Model chapter. I don't wanted to fix them as @m1cm1c has assigned for it.

**Comment by m1cm1c** [comment]
Thank you. I'll fix it.

**Comment by flyfl** [comment]
I'm not finished yet. I'm still updating my comment.

**Comment by m1cm1c** [comment]
What does `\glslabel{software architecture}` mean?

**Comment by flyfl** [comment]
Ok I'm done. All my suggestions are mentioned above.
>What does \glslabel{software architecture} mean?

I don't know.

**Comment by m1cm1c** [comment]
I'll fix them in  #237.

**Comment by m1cm1c** [comment]
> This should start with a big letter:

>    predictions suggest that small changes in
>    the software’s architecture adopting these improvements will lead to a much better
>    performance.

Nope. It says "Palladio" before the word "predictions".

**Comment by jGleitz** [comment]
Isn’t this fixed now, @m1cm1c?

**Comment by m1cm1c** [comment]
You mean whether the issue can  e closed? It can. The problem described above never existed.
