### ISSUE TITLE
Invalid path

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#215]
I can't check out anymore, because of `doc/Requirements Specification/Local Copies of Websites/2015-11-29 14:49 Committees Paper.tar`: On windows, ":" is not allowed in file/folder names.

Can someone please rename it?

(Stupid windows)

**Comment by jGleitz** [comment]
Why did that even make it into the repo? [The paper publically available](http://www.melconway.com/Home/pdf/committees.pdf) and thus surely doesn’t need to be included in the repo.

**Comment by m1cm1c** [comment]
The paper is on the authors website which might be no longer available after the author decided its no longer important or after he died.

**Comment by m1cm1c** [comment]
The paper itself isn't linked but his website on which he commented his paper. This website might be taken offline after the author decided it's no longer important or after he died.
