### ISSUE TITLE
Adopt New File Format

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#22]
In #13 we specified a file and folder name format. This has now to be consequently applied to *all* files and folders.

(Hint: Using your git tool (or `git mv`) to rename files assures git recognizes the movements instead of showing deletions and additions.)

**Comment by jGleitz** [comment]
@m1cm1c cany you do this _right now_? We don’t have any pending pull requests in the moment, but I’ll start working again soon. Now would be a perfect point to introduce this.

**Comment by m1cm1c** [comment]
Yes, I'll do it.

**Comment by jGleitz** [comment]
Nice :+1:
