### ISSUE TITLE
/P10/ grammer

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#220]
> Beagle enables the user to analyse given source code regarding the resources
its internal actions’ demand when executed.

I don'T think this is a correct sentence.

**Comment by jGleitz** [comment]
> I don'T think this is a correct sentence.

It is. But it’s complex :). Check #164 for a long discussion about this sentence.

**Comment by m1cm1c** [comment]
It should be "internal actions" instead of "internal actions".

**Comment by jGleitz** [comment]
Oh, yeah, we missed that.
