### ISSUE TITLE
/F20/ spelling

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#221]
> Beagle conducts measurements of the sections found by /F10/ by utilising
measurement softwares.

I don't think there is a plural of software.

**Comment by jGleitz** [comment]
> I don't think there is a plural of software.

Absolutely true.

**Comment by m1cm1c** [comment]
Blocked by #198.

**Comment by m1cm1c** [comment]
Unblocked because I'll handle it simultaneously with #198.
