### ISSUE TITLE
SRS: References to tests are broken

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#238]
This is unfortunate, but as they are only referenced in comments, this does not need to be fixed before the SRS is handed in.

It should, however, be fixed to assure the SRS’ quality.

**Comment by RomanLangrehr** [comment]
All internal links are broken. (To Terms and Definition and to Bibliography, too)!

**Comment by RomanLangrehr** [comment]
There is a commit `fixed broken reference` from @jGleitz 
Is this solved?

**Comment by jGleitz** [comment]
Nope, this was only a hotfix for the references “tests -> requirements”. This issues is about the references “requirements -> tests” which are annotated in LyX notes.
