### ISSUE TITLE
Find Classes: Chapter 7 Test Cases

### ISSUE THREAD

**Issue by flyfl** [Beagle-PSE/Beagle#253]
Extract in regard to the linguistic analysis (SWT lecture 2.5) relevant public members.

| word class | element | example |
|:-----------|:------------|:------------|
|noun|class|car, dog|
|name|instance|Peter|
|intransitive verb|message|running, sleeping|
|transitive verb|association|eat STH., love SO.|
|"to be"|inheritance|"is..."|
|"to have"|aggregation|"has a..."|

**Comment by flyfl** [comment]
I could not find any new classes within this section. But two question have arose:

- Do we need to define our own exceptions?
- Any mention of the test cases and their structure in our class diagram? (or anywhere else in the design specification?)

**Comment by jGleitz** [comment]
> Do we need to define our own exceptions?

If needed, I guess. But I can’t think of any meaningful Exception in the moment.

> Any mention of the test cases and their structure in our class diagram?

I don’t thing that’s necessary.
