### ISSUE TITLE
Travis is Failing

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#260]
Why is Travis failing for #258? Only images for meeting minutes have been added. All other commits and accepted PRs also just add new images.

After I merged #257 (which also just adds a new image and has no Travis errors) [this is happening](https://travis-ci.org/Beagle-PSE/Beagle/builds/96395729).

**Comment by jGleitz** [comment]
@RomanLangrehr: is this still an issue?

**Comment by RomanLangrehr** [comment]
No
