### ISSUE TITLE
Checkstyle

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#265]
As we want to start Implementing soon, we need a Checkstyle.
Does anyone have any wishes or preferences for this?

I am going to create a Checkstyle document trying to specify every rule possible. Any suggestions?

**Comment by jGleitz** [comment]
Please allow inline conditionals ( ? : )!

**Comment by m1cm1c** [comment]
Please make sure that a file for Eclipse code formatting which complies with your checkstyle rules exist or create such a file / adapt an existing file to obey all rules.

**Comment by acBerger** [comment]
I applied your suggestions.
