### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#266]
As we want to start Implementing soon, we need a Formatter.
Does anyone have any wishes or preferences for this?

I am going to create a Formatter document trying to specify every rule possible. Any suggestions?

**Comment by RomanLangrehr** [comment]
I like tabs for intendation (not spaces) and a intendation width of 2, but 4 is OK, too.

**Comment by jGleitz** [comment]
> and a intendation width of 2

one major advantage of tabs is that you can specify the width yourself, isn’t it?

**Comment by RomanLangrehr** [comment]
> one major advantage of tabs is that you can specify the width yourself, isn’t it?

No, we had problems with this during the programming final exams: When you use different tab widths, line breaks are different. And that destroys the git diff.

**Comment by jGleitz** [comment]
> No, we had problems with this during the programming final exams: When you use different tab widths, line breaks are different. And that destroys the git diff.

Oh, yeah, I remember. But there **has** to be a setting to differentiate between displayed tab width and the one used to calculate line breaks!

**Comment by acBerger** [comment]
I selected "tab" everywhere it was possible and if they asked for intendation in spaces I entered 4, as I like that more. We have to test later if there are problems if some use 4 and some use 2. Maybe we can solve that.
