### ISSUE TITLE
Build Tool

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#268]
In SWT we used Maven for building our project. We need something similar too.

Does anyone know another build tool? Do we want to use Maven as we all already know it?

Please share your thoughts below.

**Comment by jGleitz** [comment]
During the SWT lecture, Maven gave me (and many others) headaches. Meanwhile, I know that there exist build tools that make building a breeze (e.g. Grunt (for JavaScript) and Ubuntu Click). Maybe we should try Gradle. I have no experience with it, but read good reviews about it.

**Comment by RomanLangrehr** [comment]
I like maven pretty much, but I have verry little experince with other build tools.

**Comment by jGleitz** [comment]
I read through the Gradle docs and am now quite convinced we should give it a go. My personal selection of arguments:

 * Gradle uses a lot of Maven’s conventions. It’s likely we’ll find most things we like about Maven in Gradle
 * Gradle tries hard to generate a user friendly log. I hate how a typical Maven build gives you 300+ lines of output although there were no errors.
 * Gradle uses a JSON-like syntax for configuration. I find it very intuitive.
 * Unlike Maven, Gradle has a great website documenting how to get stuff done.

Gradle gives [a bunch of other (naturally biased) arguments](http://gradle.org/maven_vs_gradle/)

What do you think?

**Comment by viridispirus** [comment]
Gradle is a good tool I think.

**Comment by jGleitz** [comment]
I tried the whole evening to setup Gradle. Setting up Gradle itself was easy, but its Eclipse plugin is a a pain in the ass.

Needs further investigation.
