### ISSUE TITLE
Prototype for Palladio API

### ISSUE THREAD

**Issue by flyfl** [Beagle-PSE/Beagle#279]
Find out, how to access RDSEFFs, SEFF loops and SEFF branches from the PCM. Therefore create a  prototype that reads and manipulates these components.

**Comment by jGleitz** [comment]
How’s progress on this?

**Comment by jGleitz** [comment]
We don’t need a prototype because we merged the code into `master`. So we can close this issue, can’t we?

**Comment by RomanLangrehr** [comment]
I agree.
