### ISSUE TITLE
@version tag

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#282]
The code templates add an `@version` tag to every class.

I don't like them, because I dont want to increase this number every time I edit a file.

**Comment by jGleitz** [comment]
I see that it’s annoying to update `@version`. On the other hand, I think it provides useful version information (but I’m not sure if there is a scenario in which we’ll actually make use of it).

**Comment by jGleitz** [comment]
We decided not to use `@version` tags.
