### ISSUE TITLE
How defensive do we program?

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#285]
“defensive programming” describes a way programming giving users of an API detailed error messages when they use an API wrong, for instance (but not limited to) by checking input arguments. This might lead to less bugs. 

non-defensive programming puts the method’s contract above anything. If the programmer breaks the contract by providing bad input, it’s “his fault” and the API has undefined behaviour¹.

For example, a method may return useable, but false values. Defensive programming would check the input arguments and throw an exception and prevent the programmer from continuing with false values. 

I think we should agree on an consistent style. Please note that defensive programming requires more unit tests!

¹ as some of us learned in ICPC, undefined behaviour may include erasing your hard drive ;)

**Comment by jGleitz** [comment]
Another aspect of defensive programming is whether Arrays or Collections are copied before being handed out via getters.

**Comment by RomanLangrehr** [comment]
We decided to develop as defensive as possible.
