### ISSUE TITLE
Define project language(s)

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#3]
I think we should clearly state which language to use at which part of the project and strictly stick to these decisions. I suggest to decide on the language to use at these parts of the project:

 * Source code identifiers (e.g. variables)
 * Source code comments ( <=> Javadoc)
 * Commits
 * GitHub (Pull Requests, Issues, ...)
 * General Documentation (e.g. system specification)

I think we should never use different languages for the same part. 
I personally like source code identifiers and comments (Javadoc) to be in English, because switching languages in one document is hard for me (as programming languages are always in English).
Furthermore, I'm used to write English for commits and GitHub. If we have that, it would only make sense to write documentation in English too, to have an all English repository.

Using only English will likely be a challenge for the most of us, including me. On the other hand, it will certainly be good practice. 

We will have to ask the SDQ if they have any requirements for the language used. But first I'd like to hear your thoughts on this!

**Comment by jGleitz** [comment]
Some updates from today's metting:

 * source code indentifiers and JavaDoc will certainly be English
 * The SDQ does not put up any requirements but prefers English


As a consequence, I propose to do everything in English, as discussed today.

As I'm unsure whether we have made a final decision yet, I'd like to hear your thoughts.

**Comment by m1cm1c** [comment]
In my opinion, everything either on or eventually going to GitHub (including documentation as well as any documents which will be created in the course of this project) should be in English. Team conferences (meetings, Hangouts) should be in German.

**Comment by viridispirus** [comment]
I think, we shall make the comments in GitHub in German. By reason that we can´t say accurately sometime what we want to say. And have than the danger to talk past each other.

**Comment by flyfl** [comment]
I guess the english language will be a real challange to explain everything as clear as possible, like viridispirus said (especially if one is not used to). Nevertheless I also think practising English is an advantage for all of us, in regard to further projects or conversations. So I would agree to make use of English.
In case that we at some point arrive at an increadibly hard issue that may take endless efford to discuss, we should reserve the option to switch to German anyway.

**Comment by jGleitz** [comment]
I like @flyfl's idea of German as a fallback language that preferably will never be used.

If I get this right, we vote like 3 for all English and 1 for GitHub comments in German.

@acBerger, @RomanLangrehr, what do you say?

**Comment by acBerger** [comment]
I do not see any problem in switching the language in Git-Diskussion, Issues or Comments if necessary. As the code, and most of the Information, is in English I prefer trying to write in English.

**Comment by viridispirus** [comment]
I've thought about it again, and  now I agree with the idea from @flyfl.

**Comment by RomanLangrehr** [comment]
I still think that german would be better, as communication is much easier in german for all of us.
On the other hand, when we make everything in english, we avoid problems with the translation of technical terms.

**Comment by jGleitz** [comment]
> I still think that german would be better

Which parts of the project are you referring to?

**Comment by RomanLangrehr** [comment]
> Which parts of the project are you referring to?
Discussions and issues.
I think we already disscussed that everything else (especially documents) will be in english.

**Comment by m1cm1c** [comment]
After reading through the translated notes and this discussion, I think that maybe we really should keep notes and discussions in German, as I can see that some of you have problems with actualization, which could and will lead to reduced communication.

**Comment by jGleitz** [comment]
> I can see that some of you have problems with actualization

You meant to say "articulation", didn't you? If not, please elaborate on what our [actualization](http://dict.leo.org/ende/index_de.html#/search=actualization&searchLoc=0&resultOrder=basic&multiwordShowSingle=on) lacks! ;)


> which could and will lead to reduced communication

When developing [JUnit-KIT](https://github.com/jGleitz/JUnit-KIT), we did everything in English, and had quite lively discussions. I think we should give ourselves some time to get used to communicating in English. I really don't hope people cease to interact just because of language issues.
Most software is developed in English, and most of the times, the developers don't speak better English than we do. 

We will write documentation in English, and everybody has to write documentation. Language mistakes in GitHub comments are not a big deal, language mistakes in documents are. So why don't we use the comments to practice?

I vote for doing everything in English. But I don't have a problem with commenting in German, too.

**Comment by m1cm1c** [comment]
Yeah ...
![](http://orig02.deviantart.net/96a2/f/2015/097/2/3/bloggif_552473d0833d6_by_warnersegamaster-d8ov863.gif)

**Comment by jGleitz** [comment]
As decided in meeting 2015-11-17, 

 | everything either on or eventually going to GitHub

must be in English.
