### ISSUE TITLE
Create Working Beagle Core Implementation

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#300]
Based on the stubs of #298, the Beagle Core component shall be implemented. This implementation does not need to think of or handle all details and edge cases, but rather ensure we get a running version of Beagle as soon as #295 and #279 produced results.

**Comment by RomanLangrehr** [comment]
I think we should split this into multiple tasks, that can be implemented separtly.
[My proposal](https://www.dropbox.com/s/49jt0u5rhrnmiq4/Beagle_Core.PDF?dl=0)

Opinions?

**Comment by jGleitz** [comment]
Looks reasonable to me.

**Comment by jGleitz** [comment]
@RomanLangrehr, will you add issues according to your proposal?

**Comment by RomanLangrehr** [comment]
Yes, when your stub PR is merged.

Am 24. Dezember 2015 08:36:11 MEZ, schrieb Joshua Gleitze <notifications@github.com>:
>@RomanLangrehr, will you add issues according to your proposal? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/issues/300#issuecomment-167061248

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
