### ISSUE TITLE
Build eclispe plugins with gradle.

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#307]
I think this task can get pretty challenging.
[This](https://github.com/akhikhl/wuff) is the only tool I found after searching for a few minutes, that does what we want and is still under development.

**Comment by jGleitz** [comment]
Well, that looks proming, doesn’t it?

I think it’s likely that we’ll have to get our hands dirty to achieve automatic builds. But if there is already a project we can contribute to, that makes stuff a lot easier.

**Comment by jGleitz** [comment]
Done.
