### ISSUE TITLE
Define required interfaces

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#31]
The SRS has to clearly state on which software and interfaces our project depends. This will mainly take place in the “environment” chapter.

**Comment by acBerger** [comment]
@viridispirus  and @jGleitz did "Environment", which includes this. So it should be okay now.

**Comment by jGleitz** [comment]
> So it should be okay now

It’s a starting point but will certainly need further improvement. Leaving this therefore open.

**Comment by jGleitz** [comment]
The component diagram and Evironment chapter should state this sufficently. Please open a new issue for any desired corrections.
