### ISSUE TITLE
final judge view

### ISSUE THREAD

**Issue by viridispirus** [Beagle-PSE/Beagle#313]
I don't know which methods the `Final Judge View` in the model should have.
Did it got the hole blackboard?

**Comment by RomanLangrehr** [comment]
I think the same as the read only blackboard view plus some `set final ... ` for loops/branches/RDIAs

**Comment by viridispirus** [comment]
Ok, thanks.

**Comment by jGleitz** [comment]
We discussed that a final judge should also be able to dispatch Measurements to be measured again as well as contribute (non-final) EvaExs.

**Comment by viridispirus** [comment]
> as well as contribute (non-final) EvaExs.

in which kind can the final judge constribute?

**Comment by RomanLangrehr** [comment]
It can add final Evaluable Expressions

**Comment by viridispirus** [comment]
>It can add final Evaluable Expressions

Is this method still missing or did that the `set final...` methods that?

**Comment by jGleitz** [comment]
Is there still any work left to do on this after #408?

**Comment by viridispirus** [comment]
I think not.
