### ISSUE TITLE
German checkstyle meassages

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#316]
... should be translated into english.

I found:
 * Der erste Satz sollte mit einem Punkt abschließen

**Comment by jGleitz** [comment]
Did you find that in the xml file? Because then we should fix it. 

I thing that the Eclipse plugin is translating the messages. In that case, there is nothing we can or should do about it.

**Comment by RomanLangrehr** [comment]
I see, sorry, it's not in the xml file.

Just why on earth is checkstyle translating in an english IDE it's own messages into german?

**Comment by jGleitz** [comment]
> Just why on earth is checkstyle translating in an english IDE it's own messages into german?

That’s a good question. I like the idea of translating those message, but the translation is so bad that I’d like to disable it.
