### ISSUE TITLE
Inconsistent import order.

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#317]
The import order in the file `mport Order` is different to the import order checkstyle expects.

E.g. the formatter puts `org` before `java` and checkstyle is not amused about it.

**Comment by jGleitz** [comment]
Did you check with the latest version of the file? (Changes to the file do not update the project)

**Comment by RomanLangrehr** [comment]
> Did you check with the latest version of the file? (Changes to the file do not update the project)

I got this message after saving and building the project.
