### ISSUE TITLE
[Checkstyle] Line Breaks at End of File

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#319]
I often get the error message `Datei endet nicht mit einem Zeilenumbruch.` from checkstyle, even my files end with an line break.

Maybe there is a problem with windows-style line endings?

**Comment by jGleitz** [comment]
Does adding another newline solve the issue?

**Comment by m1cm1c** [comment]
You can change your line breaks to unix in Eclipse. I thought we already did this (and found out that Eclipse removed the option to set it to Mac line breaks). Or maybe it was with @viridispirus.

**Comment by m1cm1c** [comment]
> Does adding another newline solve the issue?

Windows line breaks are `\n\r`. So adding another one makes it `\n\r\n\r` which still has no `\n` in the end.

**Comment by jGleitz** [comment]
> You can change your line breaks to unix in Eclipse

This is not how this should work. git handles newline conversion, such that everybody can use the newlines that are native on his/her system.

**Comment by jGleitz** [comment]
Checkstyle is configured to expect the system-native line endings:

![cs-newline](https://cloud.githubusercontent.com/assets/4305652/12008186/4c59ae38-ac2b-11e5-982b-3b039d412224.png)

So maybe the problem is that you set Eclipse to use `\n` instead of `\n\r` which any program would expect on windows?

**Comment by RomanLangrehr** [comment]
> So maybe the problem is that you set Eclipse to use \n instead of \n\r which any program would expect on windows?

That was the problem. Thanks.
