### ISSUE TITLE
Checkstyle intendation of }

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#320]
![image](https://cloud.githubusercontent.com/assets/10776736/12002635/927e4d70-ab03-11e5-994d-78397d463293.png)

Whats the problem here? Checkstyle says: `'}' in Spalte 4 sollte auf der gleichen Linie wie der nächste Teil einer Multi-Block-Anweisung sein.`

**Comment by jGleitz** [comment]
As far as I can see, this error is meant to ensure that `else` and similar blocks are put in the same line as the closing bracket before them. But obviously, that does not make sense for a for loop...
