### ISSUE TITLE
Checkstyle Requires `this.` in Listeners

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#322]
![](http://i.imgur.com/i13eHIy.png)

This is just impossible.

**Comment by jGleitz** [comment]
> This is just impossible.

[It's not](http://stackoverflow.com/q/56974) 

Am 25.12.2015 8:14 nachm. schrieb m1cm1c <notifications@github.com>:

 

This is just impossible.

**Comment by m1cm1c** [comment]
Checkstyle accepts it. Thank you.
