### ISSUE TITLE
Checkstyle Produces Errors

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#323]
I just got this one when I pressed "ctrl + S" in the middle of editing Java code (I forgot an `=`). Is it possible to hide these messages?

![](http://i.imgur.com/QPrPHuM.png)

**Comment by jGleitz** [comment]
This occurs whenever you save in a state that throws compile errors. It's a nasty bug but it can simply be avoided by only saving when the document would compile. 

There is nothing we can do about it. Feel free to file a bug against the eclipse-cs plugin if there isn't already one. 

Am 26.12.2015 9:05 vorm. schrieb m1cm1c <notifications@github.com>:

I just got this one in the middle of editing Java code:
