### ISSUE TITLE
[Checkstyle] Variable Name Minimum Length

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#324]
![](http://i.imgur.com/FB0NShf.png)

Is there a reason for this rule? It's especially confusing to me that Checkstyle seems to be okay with variable `description`.

**Comment by acBerger** [comment]
Description is okay as it has more than 5 letters.
Am 26.12.2015 09:47 schrieb "m1cm1c" <notifications@github.com>:

**Comment by m1cm1c** [comment]
Oops, I saw the caret and thought it meant that the variable can't start with a lowercase. I forgot the special meaning of it in the beginning of a regex.

**Comment by m1cm1c** [comment]
Calling them anything other than "title" and "description" is ugly. I already changed them to "pageTitle" and "pageDescription" but removed the changes again because it feels stupid since they are attributes of a page.

**Comment by jGleitz** [comment]
We decided to lower the maximum length to 5 characters. But we also agreed to make effort to use descriptive identifier names.
