### ISSUE TITLE
Functional requirements

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#33]
The first batch of functional requirements, as discussed in the meeting on 2015-11-21, shall be written down.

They do not yet have to be worded well or even correctly. It’s only important to determine atomic requirements (bullet points are okay).

**Comment by acBerger** [comment]
We got the first bullet points in our document. This is great.
However, we should try to find some more.

**Comment by jGleitz** [comment]
Need to be extended by today’s findings!

**Comment by jGleitz** [comment]
Is there anything you miss to consider this chapter *draft ready*? This means:

 * It includes all essential content
 * It includes most optional content
 * It’s wording is understandable. (“good” wording will follow when working towards final!)

**Comment by acBerger** [comment]
I cannot think about more functional requirements and I am sure the wording is understandable.
For me it is draft ready

**Comment by acBerger** [comment]
As it seems that no one has something to add or change here, I'm going to close this.
