### ISSUE TITLE
[Checkstyle] Javadoc summary maximum length

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#332]
![image](https://cloud.githubusercontent.com/assets/10776736/12006656/c4514c76-abdf-11e5-8dab-2079567e6cbb.png)
Message: Summary too long (max 100 letters).

My JavaDoc is too long. Seriously?

**Comment by m1cm1c** [comment]
This can't be the reason. I have a javadoc entry with 110 characters (no @-tags) and am not shown this message.

**Comment by m1cm1c** [comment]
Hmm, mine is for an attribute, yours is for a method. But allowing less documentation for a method than for an attribute (or only 100 characters generally speaking) doesn't make sense.

**Comment by RomanLangrehr** [comment]
> Hmm, mine is for an attribute, yours is for a method.

No, mine is for an attribute.

**Comment by jGleitz** [comment]
Please merge with master, the limit was raised to 120 letters in one of my pull requests. 

Am 26.12.2015 2:52 nachm. schrieb m1cm1c <notifications@github.com>:

This can't be the reason. I have a javadoc entry with 110 characters (no @-tags) and am not shown this message.

**Comment by m1cm1c** [comment]
> Please merge with master, the limit was raised to 120 letters in one of my pull requests.

No, it wasn't: https://github.com/Beagle-PSE/Beagle/blob/master/src/test/Checkstyle.xml

(I can't paste the xml code here.)

**Comment by m1cm1c** [comment]
Btw.: That's for 99 characters, not for 100. And I don't know whether it does what it's supposed to do. Maybe it just makes sure no sentence has more than 99 characters.

**Comment by jGleitz** [comment]
Okay, I'm sorry. Obviously, I only planned to do it.
