### ISSUE TITLE
[Checkstyle] Parameter Length

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#333]
Minimum lengths suck in general but especially if you handle an event. Usually, people just call the variable `e`. Everyone does so. But even if you call it `event`, it's too short.

Anyone else for or against removing this rule?

I don't know yet whether this rule also applies for counting variables but using long counting variables sounds painful.

**Comment by jGleitz** [comment]
We decided to lower the maximum length to 4 characters. But we also agreed to make effort to use descriptive identifier names.

**Comment by acBerger** [comment]
This was done in #348
