### ISSUE TITLE
Environment Attributes

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#34]
The first batch of environment attributes, as discussed in the meeting on 2015-11-21, shall be written down.

They do not yet have to be worded well or even correctly. It’s only important to determine atomic attributes (bullet points are okay).

**Comment by acBerger** [comment]
We got the first bullet points in our document. This is great.
However, we should try to find some more.

**Comment by acBerger** [comment]
I removed following from 2.3 (Operation Conditions) because it should be merged with this (Environment).
- Beagle runs on desktop systems with a JRE as it is a Eclipse Plugin.
- As an optional feature, Beagle has the additional possibity to be run on a Server.

**Comment by jGleitz** [comment]
Specifiy the versions of software we are going to support.

**Comment by viridispirus** [comment]
I would prefer to support the version of software we still have.
In my case its Java 7 and eclipse mars.

**Comment by RomanLangrehr** [comment]
> I would prefer to support the version of software we still have.
In my case its Java 7 and eclipse mars.

Then please install the current Java version, Java 8, as i appreciate supporing the currently up-to-date software and most of us use Java 8.

**Comment by jGleitz** [comment]
I agree with @RomanLangrehr: Java 8 is currently recommended and state of the art. So we should specify Java 8

**Comment by acBerger** [comment]
As all above is already in Environment: is there more which belongs here? Otherwise this should be draft ready.

**Comment by jGleitz** [comment]
Does anybody have something to add to this chapter before it can be considered *draft ready*? This means:

 * It includes **all** essential content
 * It includes **most** optional content
 * It’s wording is **understandable**. (“good” wording will follow when working towards final!)

**Comment by acBerger** [comment]
As it seems that no one has something to add or change here, I'm going to close this.
