### ISSUE TITLE
[Checkstyle] Configuration for Prototypes

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#346]
The same as main Beagle but

 * Allow sysout
 * Allow main methods
 * Allow TODO

**Comment by jGleitz** [comment]
It would be nice if the prototype Checkstyle file could inherit the rules from the Beagle project Checkstyle configuration, such that changes in the latter apply to the first (except for rules overridden in the prototype configuration)

**Comment by acBerger** [comment]
I was not able to find a way to sync both checkstyle.xml files.
