### ISSUE TITLE
Package name for prototypes

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#355]
I used as package name for prototyps something like `de.uka.ipd.sdq.beagle.extensionpointprototype`, while @m1cm1c used `de.uka.ipd.sdq.beagle.prototypes.gui`

I don't prefer anyone, but we should agree on a unique style.

Any perferences?

**Comment by jGleitz** [comment]
I prefer the below.

**Comment by m1cm1c** [comment]
I chose mine spontaneously during our previous video conference and without thinking about it. While I admit that mine isn't perfect in the last part, I prefer the having package names for prototypes start with `de.uka.ipd.sdq.beagle.prototypes.`.

**Comment by jGleitz** [comment]
That’s exactly what I think: start with `de.uka.ipd.sdq.beagle.prototypes` and choose something meaningful afterwards.

**Comment by RomanLangrehr** [comment]
Alright.
