### ISSUE TITLE
CHECKSTYLE:OFF doesn't work in prototype

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#356]
I copied some stub classes in my prototype, because i need them there, but now I get checkstyle errors:
![image](https://cloud.githubusercontent.com/assets/10776736/12071520/ebe6dd66-b0b0-11e5-9e26-820cf59cd671.png)

**Comment by m1cm1c** [comment]
Please hover over them so the warning descriptions are displayed.

Have you made sure to use the Checkstyle rules for prototypes? Are you using the latest version of them?

**Comment by jGleitz** [comment]
It’s not relevant which warnings are shown – they should not be there at all, because he used `CHECKSTYLE:OFF`.

**Comment by RomanLangrehr** [comment]
> Have you made sure to use the Checkstyle rules for prototypes? Are you using the latest version of them?

Yes

**Comment by m1cm1c** [comment]
Confirmed. I have the same problem.
