### ISSUE TITLE
`=` Checkystyle vs. Formatter

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#358]
The formatter formats like this
![image](https://cloud.githubusercontent.com/assets/10776736/12071789/c6255496-b0be-11e5-9190-04be4dd0257e.png)

and checkstyle complains about it: `'=' sollte in einer neuen Zeile stehen.`

(at least in prototype checkstyle)

**Comment by acBerger** [comment]
Which version do you prefer?

**Comment by RomanLangrehr** [comment]
The formatter's one.

**Comment by acBerger** [comment]
Do you know if this occurs for every operator (eg. `+=`)?

**Comment by RomanLangrehr** [comment]
> Do you know if this occurs for every operator (eg. `+=`)?

Yes, it occurs with every operator.
