### ISSUE TITLE
Non Functional Requirements

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#36]
The first batch of non functional requirements, as discussed in the meeting on 2015-11-21, shall be written down.

They do not yet have to be worded well or even correctly. It’s only important to determine atomic requirements (bullet points are okay).

**Comment by acBerger** [comment]
We got the first bullet points in our document. This is great.
However, we should try to find some more.

**Comment by jGleitz** [comment]
The SRS still give a very rough view of our project. @viridispirus could you try to define further non functional requirements that make our software more useful?

**Comment by viridispirus** [comment]
Ok.

**Comment by viridispirus** [comment]
I reflect about two non functional requirements we shall put in the SRS but don't know how accurate write them. The first one is about the runtime of Beagle. I think it is usefull if we can say relative how long Beagle will run in dependency of the program which is analysed.

And the second is a quorum of breakpoints.

**Comment by jGleitz** [comment]
First of all: We’re still in draft mode. The important thing is that we get content in there. So please include every idea you have! They don’t need to be written down completely or correctly, the important part is that they exist!

To your points:

The runtime requirement makes sense and should theoretically be included. But its very hard to define that.

I unfortunately don’t understand what you mean with the second one.

**Comment by viridispirus** [comment]
If we can say how many breakpoints we set to measure a internal action, component, program?
Or at least, a minimun of breakpoints.

**Comment by jGleitz** [comment]
Need to be extended by today’s findings!

**Comment by acBerger** [comment]
As it seems that no one has something to add or change here, I'm going to close this.
