### ISSUE TITLE
No @author for Packages

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#363]
In the last meeting, we decided not to use `@author` in `package-info.java` files. However. the code templates still insert it. 

Best, Checkstyle would throw a warning for it.

I think that `@author` has little use for packages and needs to be updated often.

**Comment by acBerger** [comment]
Yes, you are right. I forgot to change that.

**Comment by acBerger** [comment]
I do not see any possibility to make this happen, as the template is for all generated types.
Either we remove `@author` from the template and then add it by hand when creating anything but a package-info or we remove it by hand for package-infos.

Unfortunately I did not find a way to bring up checkstyle warnings for this too.
