### ISSUE TITLE
Modifications of SRS

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#369]
Do we want to adapt the SRS? Following the document Roman found, we can change the SRS to fit to the Design.

**Comment by jGleitz** [comment]
Yes I think we should for example remove the CTA. It's a typical case to find that specifications can not be realised (and one of the major disadvantages of the waterfall model). 

Am 02.01.2016 3:37 nachm. schrieb acBerger <notifications@github.com>:

Do we want to adapt the SRS? Following the document Roman found, we can change the SRS to fit to the Design.

**Comment by flyfl** [comment]
Don't you think it would be enough to mention the missing CTA in the Design Document? I mean we couldn't foresee that. In my opinion, it is okay to have that documented.

**Comment by acBerger** [comment]
So for the Design Final we will not change the existing SRS but only mention the changes in the Design Document? This sounds okay for me.

**Comment by m1cm1c** [comment]
The advisor guy said something about writing one or two sentences more. Does anyone have ideas?

**Comment by flyfl** [comment]
Yes, that was not much. I fix this.
