### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#37]
The first batch of purposes, as discussed in the meeting on 2015-11-21, shall be written down.

They do not yet have to be worded well or even correctly. It’s only important to determine purposes  (bullet points are okay).

**Comment by acBerger** [comment]
We got the first bullet points in our document. This is great.
However, we should try to find some more.

**Comment by jGleitz** [comment]
The “Purpose” chapter is draft ready. This means:

 * It includes all essential content
 * It includes most optional content
 * It’s wording is understandable. (“good” wording will follow when working towards final!)

Please report any issues with the chapter in specific new issues.
