### ISSUE TITLE
Check Design

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#371]
We should check our Design with [Tips] (https://pp.ipd.kit.edu/lehre/WS201415/pse_lambda/tipps.pdf) to see if we got all points or first are going to do everything needed.

**Comment by flyfl** [comment]
I think the overall design is pretty well and have no more notes than following:

##PCM
![task1](https://cloud.githubusercontent.com/assets/15742643/12221887/d02cee60-b7ab-11e5-9f17-b9b897a21f7a.png)

##GUI
![task2](https://cloud.githubusercontent.com/assets/15742643/12221888/d03702c4-b7ab-11e5-8512-b1c7d1e23b3a.png)
![task3](https://cloud.githubusercontent.com/assets/15742643/12221889/d03b5fa4-b7ab-11e5-8563-39c03ea9ccb1.png)

##Measurements
- Where will the MeasurementOrders be created?

**Comment by flyfl** [comment]
Resolved by
#531 Create Classes and Javadoc for PCM
#532 Fix GUI Diagram

MeasurementOrders -> @jGleitz
