### ISSUE TITLE
Update Java Files According to Current Design

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#375]
The Java files need to be updated according to the current design.

**Comment by viridispirus** [comment]
To which state of our design model shoud I check, with my last PR  #351 or not?

**Comment by RomanLangrehr** [comment]
I think it's best with #352 . I'll do this immediatly, when your PR is merged.

**Comment by viridispirus** [comment]
I found a `MeasurementControllerBlackboardView` class. In the beagle core UML model we only have the `Measurement View` class. Are this two classes the same?

**Comment by jGleitz** [comment]
Yes. I already commented on one of the your old PRs that I’d like the classes to be named “[User] Blackboard View”, e.g. “Measurement Controller Blackboard View” and “Final Judge Blackboard View” in the UML diagrams, too.

**Comment by viridispirus** [comment]
So, I finished comparing the model with our current code stumps. A lot of them are equal as @RomanLangrehr said. But some methods are missing. The most of them are getter methods in the views. Do we need to write for all getter in the Views method stumps?

**Comment by jGleitz** [comment]
I think we do, yes. But please note that Eclipse offers a functionality for that. As soon as the Blackboard had these methods, Eclipse can create composition objects. These will delegate selected methods and automatically create Javadoc pointing to the original method on the blackboard. We should make use of this functionality.

**Comment by viridispirus** [comment]
Ok, thanks.

**Comment by viridispirus** [comment]
For all found disparity are now new Issues opened in: #402, #403, #405, #406.
