### ISSUE TITLE
Papyrus: Model X

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#379]
Model the X at an association which indicates that navigation is not possible.

**Comment by viridispirus** [comment]
I researched for it and think that Papyrus doesn't give as the ability to model that 'leagal'. So I began to hack...and found a way to solve our problem. Its a bit dirty but its a way. We can give the association names and when we name them 'X' and put them to the end of the association it looks like what we want.

**Comment by jGleitz** [comment]
I don't think it's that important to convey non-navigatebility. What do the others think? 

Am 04.01.2016 4:14 nachm. schrieb Micha <notifications@github.com>:

I researched for it and think that Papyrus doesn't give as the ability to model that 'leagal'. So I began to hack...and found a way to solve our problem. Its a bit dirty but its a way. We can give the association names and when we name them 'X' and put them to the end of the association it looks like what we want.

**Comment by RomanLangrehr** [comment]
> I don't think it's that important to convey non-navigatebility. What do the others think?

I agree.

**Comment by acBerger** [comment]
> I don't think it's that important to convey non-navigatebility. What do
the others think?

I agree.

2016-01-04 16:34 GMT+01:00 Roman Langrehr <notifications@github.com>:

**Comment by viridispirus** [comment]
Agree to.
