### ISSUE TITLE
Model a simple Exemplary Run of Beagle

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#390]
This should be done in the form of a sequence diagram (and is a lot of work).

**Comment by jGleitz** [comment]
I think this should be done using a reasonable amount of plugged in ResultAnalysers to point out how our design makes collaboration and feedback between them really easy. 

Am 03.01.2016 11:16 vorm. schrieb m1cm1c <notifications@github.com>:

This should be done in the form of a sequence diagram (and is a lot of work).

**Comment by RomanLangrehr** [comment]
Should this diagram be included in the Design document? Because I think it's hardly possible, that it will fit an A4 page.

**Comment by jGleitz** [comment]
Why not? I thing the sequence diagram does not have to contain all method calls that actually take place, but a suitable selection.

**Comment by jGleitz** [comment]
Plus, I think it could easily be continued on another page (if Papyrus supports that)
