### ISSUE TITLE
Create Measurement API

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#393]
The interface `MeasurementTool` needs to be filled with content so that it's possible to use Kieker with it.

Additionally, the PCM elements classes (see #455) need to be extended to point to source code sections.

**Comment by acBerger** [comment]
Blocked until @jGleitz finished the Kieker Prototype

**Comment by RomanLangrehr** [comment]
I don't think, this has to be blocked. The interface just has no methods yet.

**Comment by jGleitz** [comment]
My prototype will mainly affect how `Measurement Order` looks like.
