### ISSUE TITLE
Create Dummy Methods (1)

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#402]
For classes:
  * ReadOnlyBlackboardView
  * AnalyserBlackboardView
  * MeasurementBlackboardView
  * FinalJugdeBlackboardView

**Comment by RomanLangrehr** [comment]
* Measurement Controller BlackboardView

is missing

**Comment by RomanLangrehr** [comment]
Something like an addMeasurementResult is missing in the diagram, too.
