### ISSUE TITLE
Add the EvaluableExpressionVisitor interface in the model

### ISSUE THREAD

**Issue by viridispirus** [Beagle-PSE/Beagle#405]
This interface should have the following methods:

	void visit(AdditionExpression expression)
	void visit(MultiplicationExpression expression)
	void visit(EvaluableVariable variable)
	void visit(ComparisonExpression expression)
	void visit(ConstantExpression constant)
	void visit(DivisionExpression expression)
	void visit(ExponentationExpression expression)
	void visit(ExponentialFunctionExpression expression)
	void visit(IfThenElseExpression expression)
	void visit(LogarithmExpression expression)
	void visit(NaturalLogarithmExpression expression)
	void visit(SineExpression expression)
	void visit(SubstractionExpression expression)

**Comment by acBerger** [comment]
There is an `EvaluableExpressionVisitor` interface containing the above mentioned methods.
