### ISSUE TITLE
Add missing methods in model

### ISSUE THREAD

**Issue by viridispirus** [Beagle-PSE/Beagle#406]
In ``Measurement Tool`` interface missing the `void measure(MeasurementOrder measurements)` and in ``Measurement Controller`` the `canMeasure(ReadOnlyBlackboardView blackboard)` method is still missing. Please add them to the model.

**Comment by RomanLangrehr** [comment]
>  in Measurement Controller the canMeasure(ReadOnlyBlackboardView blackboard) method is still missing.

Are you sure? I'm pretty sure it is there.
