### ISSUE TITLE
Checkstyle: <p> tag formatter vs. checkstyle.

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#411]
![image](https://cloud.githubusercontent.com/assets/10776736/12079291/9d4455a6-b233-11e5-8c76-75b562dc28c0.png)

I like to have <p> in a new line, but the formatter doesn't.

**Comment by jGleitz** [comment]
You have to use 2 new lines.

**Comment by RomanLangrehr** [comment]
> You have to use 2 new lines.

That doesn't work either.

**Comment by jGleitz** [comment]
Oh. That was what worked for me the last time I had this issue.
