### ISSUE TITLE
Checkstyle: Imports for Javadoc.

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#412]
I need some imports onyl for the Javadoc, and checkstyle thinks, that they are unused:
![image](https://cloud.githubusercontent.com/assets/10776736/12079295/df9ca7a0-b233-11e5-9e3e-9e9bf1fb1926.png)

Can we remove this rule, please. Unused imports are removed by the formatter anyway.

**Comment by jGleitz** [comment]
Well they are unused. Why not using fully qualified names in the javadoc?

**Comment by RomanLangrehr** [comment]
> Well they are unused.

No, they are used in JavaDoc

> Why not using fully qualified names in the javadoc?

It's really bad readable.

**Comment by jGleitz** [comment]
> This would be a workaround for a checkstyle bug and makes the JavaDoc unreadable.

It does not affect the representation in the Javadoc, as Javadoc can be configured to not print the fully qualified names. And I don’t think it’s a workaround. I think imports are for code, nor for documentation.

**Comment by RomanLangrehr** [comment]
> It does not affect the representation in the Javadoc,

But the JavaDoc of the source code, we will use probably pretty often.

> I think imports are for code, nor for documentation.

I think they are for everything in the .java file.

**Comment by jGleitz** [comment]
Checkstyle offers an option to consider Javadoc for imports. A quick research showed me that this topic is discussed controversially and there seems to be no best practice on whether to use imports for Javadoc or not. So let’s vote about this.

**Comment by m1cm1c** [comment]
Only in prototypes. The imports will be used in the final version of the classes anyway.

**Comment by RomanLangrehr** [comment]
No, we are not talking about a prototype here.

**Comment by jGleitz** [comment]
> The imports will be used in the final version of the classes anyway.

Not necessarily, there may always be cases where you want to reference a type in the Javadoc you do not use in the code.

**Comment by jGleitz** [comment]
As nobody seems to be interested in discussing this, let’s do it like @RomanLangrehr proposes. @acBerger, please adapt the checkstyle config accordingly!
