### ISSUE TITLE
Checkstyle: Summary too long

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#413]
Can we please remove this rule or at least allow more letters?

My summary `Causes the available measurement tools to measure everything which is marked as 'to be measured' as far as the measurement tools are able to do this.` is in my point of view not too long!

**Comment by jGleitz** [comment]
From my point of view, it is. This is already an almost complete definition of the class’ behaviour. The summary should only give a rough overview. Like: “instructs all available measurement tools to measure all items marked as ‘to be measured’”.

**Comment by RomanLangrehr** [comment]
Well, then the summary will be pretty duplicated to the remaining JavaDoc.

**Comment by jGleitz** [comment]
> Well, then the summary will be pretty duplicated to the remaining JavaDoc.

Why?

Instructs all available measurement tools to measure all items marked as “to be measured”. Measurement Tools may not produce results for every item but will report results for all items they are able to measure.

<p> This method may only be called, when {@link #canMeasure(ReadOnlyBlackboardView)} returned {@code true} before and the blackboard wasn't changed between this call.

**Comment by RomanLangrehr** [comment]
Alright.

I still think a limit like "maximum 120 letters" makes no sense.

**Comment by jGleitz** [comment]
> I still think a limit like "maximum 120 letters" makes no sense.

The point is that I think that you just offered a perfect example for why it makes sense: The shorter version makes it more easy to understand what the method will do **when viewing it in the overview**.
