### ISSUE TITLE
Arguments passed to Beagle Controller

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#414]
We should carefully define which parameters are passed to Beagle Controller (and how). I think that this should happen in the constructor instead of the `main` method.

**Comment by jGleitz** [comment]
Proposal: A `Beagle Controller` gets instanciated with a pre-filled blackboard and leaves its results on the Blackboard.

The logic creating a Blackboard out of PCM files as well as writing results on the Blackboard back into the PCM is put into independent classes.

**Comment by flyfl** [comment]
`The logic creating a Blackboard out of PCM files as well as writing results on the Blackboard back into the PCM is put into independent classes.`
That sounds like we need to add a package for the blackboard logic.

**Comment by jGleitz** [comment]
fixed by #456
