### ISSUE TITLE
Methods/Attributes Naming Convention

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#428]
We should agree on how we name methods. I googled it and found different conventions, all of which have in common that methods and attributes are written in lowercase or are written in lowercase if they exceed a minimum length (one was with words up to 2 letters being written in capitals, one with 3, and some (including [this one which I like](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case)) writing all acronyms like normal words. But in all cases it'd be `seffLoop`, not `SEFFLoop`.

Furthermore, we need to decide when to write something as an acronym and when not. This is very apparent on `ResourceDemandingInternalAction`/`RDIA`. I personally don't care the slightest whether we write it out in full or use `RDIA`, but we should settle for one.

**Comment by jGleitz** [comment]
I agree that we have to settle for a consistent style. I like the Google style. (But only for methods, I thing the classes should still be called `SEFFLoop`.

The second part is harder. the word is quite long, so I tried to use its full form in its definition and used the abbreviation for references. I see that this is not very consistent.

**Comment by acBerger** [comment]
As nobody else seems to have something to add here we should stick to the suggested Google style.
