### ISSUE TITLE
Model Blackboard Storer in class diagram

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#434]

**Comment by viridispirus** [comment]
Did we document something about the Blackboard Storer? I don't find anything in the Meeting Minutes.

**Comment by jGleitz** [comment]
No, it’s an interface I’ve invented while creating the stubs. It was discussed in the last meeting before the christmas holidays, but no minutes exist of that meeting.

For the class diagram, it’s enough to simply add the interface. We should then think of a way to state that the Final Judge an Result Analysers (and maybe the Measurement Controller and the Beagle Controller) may optionally implement this interface.

Maybe a “use” relation is best here? Can somebody try to look that up?

**Comment by flyfl** [comment]
I'm not really sure why we want to use a BlackboardStorer (maybe I've forgotten), but if you want to, I think the use-relation fits. But that means, that the FinalJudge and ResultAnalyser will not implement this interface (why should they?).

**Comment by jGleitz** [comment]
Maybe we should leave the interface out of the class diagram as it's essentially just a implementation detail to ensure type safety.

**Comment by viridispirus** [comment]
Are you sure?

2016-01-05 14:23 GMT+01:00 Joshua Gleitze <notifications@github.com>:
