### ISSUE TITLE
Enforce Consistent Javadoc Style in Existing Documents

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#436]
I think a consistent style for Javadoc is really important. This issue means to collect and discuss these style.

My list so far:

* [ ] Naming conventions (see also #428)
* [ ] **Everything** is a sentence:  (This is very inconsisten for `{@param}` and `{@return}` in the moment)
     * => Starts with a capital
     *  => Ends with a full stop.
* [ ] Every `{@param}` and `{@return}` states the value’s range. For object types, this should always include to state if it can be `null` and if yes, what that means.

**Comment by acBerger** [comment]
I think it is often strange to have a full sentence for `{@param}` and `{@return} as both kind of start a sentence.

**Comment by flyfl** [comment]
Agreed. @acBerger Then let us just stick to the rule
- capital start
- full stop end

**Comment by m1cm1c** [comment]
@acBerger: In Javadoc, there's a colon after "Returns" so we can simply write what it returns or write a full sentence because no sentence has been started (which would be the case if there was no colon). I agree with @jGleitz in all points.

**Comment by RomanLangrehr** [comment]
And I want to propose, that we never add the package, when using @link or @see, except if it's necassary, as we have lines that can't be formatted any more, because the @links/@sees get too long.

**Comment by jGleitz** [comment]
We first of all should get the Formatter rto break those lines!

**Comment by acBerger** [comment]
Please stick to the convention when creating new Javadoc.

This isssue stands for the task to go through all existing javadoc and adapt it to the convention.

**Comment by viridispirus** [comment]
#471
