### ISSUE TITLE
Checkstyle: Summary too long

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#438]
I'm getting tiread of this.

But: I wanted to add to the JavaDoc
```
 Adds {@code expression} as a proposal to describe {@code rdia}’s
 measurement results’ parametric dependencies.
```
an `evaluable` before expression. But then I get this checkstyle warning. This is stupid, isn't it?
Can we remove this rule?

**Comment by m1cm1c** [comment]
I don't get an error message for this but need 8 more characters to get one which makes for some pretty bad inequality. I agree that this should be accepted as a summary.

**Comment by RomanLangrehr** [comment]
A better example:
![image](https://cloud.githubusercontent.com/assets/10776736/12120212/130e7418-b3d0-11e5-98a9-1a433d960ac6.png)

Any ideas in shortening this sentence?!

**Comment by m1cm1c** [comment]
It's pretty obvious that we need to abolish this limit.

**Comment by jGleitz** [comment]
Can we compromise to remove the maximum length but to try to keep sentences as short as possible (includes that according suggestions are implemented in PRs)?

I see your trouble, but also think that keeping the summary as short reasonably possible is very important.

**Comment by m1cm1c** [comment]
As no one seems to have a problem with this, it is decided.
