### ISSUE TITLE
Rename `Beagle Controller`

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#442]
Especially if the design I proposed in #414 is adopted, `Beagle Controller` is responsible of conducting Measurements & Analysis. The name `Beagle Controller` is then misleading, a it sounds like it’s controlling the whole execution of Beagle.

I propose to rename it to `Analysis Controller`. Of course, it also controls measurements and the name can be confused with `Result Analyser`. Can you think of a better name?

**Comment by acBerger** [comment]
I found `Beagle Controller` misleading too. 

As the analysis for me also contains measurement (as they are needed before analysing) `Analysis Controller` is okay for me.

**Comment by flyfl** [comment]
Agreed. A `BeagleController` should be responsable for conducting all software components.

**Comment by jGleitz** [comment]
So I think this is decided.

**Comment by jGleitz** [comment]
fixed by #456
