### ISSUE TITLE
Explain extension point

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#443]
Explain that measurement tools are pluged in via an eclipse extension point.

**Comment by jGleitz** [comment]
`Result Analyser`s and the `Final Judge` too!

**Comment by RomanLangrehr** [comment]
Are they plugged in as extension point, too?

**Comment by jGleitz** [comment]
I thought so. For `Result Analysers` this would make a lot of sense, as third party developers could easily add some.

For the `Final Judge` it would be necessary to be able to configure which one to use if there are multiple ones found.

**Comment by RomanLangrehr** [comment]
> For the `Final Judge` it would be necessary to be able to configure which one to use if there are multiple ones found.

That can be done in the GUI for example.

**Comment by jGleitz** [comment]
> That can be done in the GUI for example.

Yes. So we enable extension points for all three?

**Comment by RomanLangrehr** [comment]
I think it's a good idea.
