### ISSUE TITLE
Model GUI

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#445]
(you can check off subtasks to report progress. This issue might be split up into multiple PRs)

* [ ] Model classes needed for the GUI
   * [ ] must use Model-View-Controller
   * [ ] must be compatible to Eclipse’s GUI framework
* [ ] Create class stubs for the GUI
* [ ] Document the stubs with Javadoc
* [ ] write the chapter about the GUI in the design document

**Comment by m1cm1c** [comment]
Done.
