### ISSUE TITLE
Different Naming of "ParameterizisedMeasurementResult"

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#450]
In the code it is called `ParameterisationDepentMeasurementResult` and in the Diagram `ParameterizisedMeasurementResult`.

Which one do you prefer?

**Comment by m1cm1c** [comment]
The first one. But they're both spelled incorrectly (the first one uses a non-existent word and the second one is in American English).

**Comment by jGleitz** [comment]
Agreed. Should be `ParameterisationDependentMeasurementResult`.

**Comment by acBerger** [comment]
Both of the spelling mistake are my fault. They are spelled right in the diagram and the code.
