### ISSUE TITLE
Store proposed and final expressions in the elements themselves

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#454]
I’ve thought through our design and thought that maybe, storing proposed and final expressions in the elements they describe might make more sense. Some arguments:

 + the expressions describe different things and should thus not be handled uniformly
 + putting them into the elements gives us a chance to document what they describe

 - our view system must be adapted and will get more complex

**Comment by flyfl** [comment]
If we do so, I think it makes sense to define our own RDIA-, SeffLoops and SeffBranch- Classes?
(That was a question, arised when I have dealt with the PCMAdapter)

**Comment by jGleitz** [comment]
> If we do so, I think it makes sense to define our own RDIA-, SeffLoops and SeffBranch- Classes?

What do you mean with this? `ResourceDemamdingInternalAction`, `SEFFLoop` und `SEFFBranch` are in `master` for quite a long time now. An I understanding you wrong?

**Comment by flyfl** [comment]
Oh I'm sorry, of course they are... I cancel my question.

**Comment by RomanLangrehr** [comment]
We decided not to do this.
