### ISSUE TITLE
Use Superclass for RDIAs, SEFFBranches and SEFFLoops

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#455]
I wanted to put up this discussion again. Some arguments:

 + does no harm
 + makes it easier to talk about all three at once
 + could simplify some interfaces where distinction is no necessary (e.g. the Blackboard)

**Comment by jGleitz** [comment]
Another argument: Final Judges will often judge proposed expressions uniformly for each element.

**Comment by acBerger** [comment]
I like the idea.
Am 06.01.2016 21:07 schrieb "Joshua Gleitze" <notifications@github.com>:

**Comment by flyfl** [comment]
Another argument: I don't think it is a big deal to throw this idea away, if we see we don't take care of it.
Therefore: Agreed.

**Comment by jGleitz** [comment]
So I take this a decided.

**Comment by acBerger** [comment]
Any suggestions for a fitting name for this super class?

**Comment by jGleitz** [comment]
`Measurable SEFF Element` ?

**Comment by RomanLangrehr** [comment]
:+1:

**Comment by flyfl** [comment]
Agreed

**Comment by acBerger** [comment]
Agreed

**Comment by jGleitz** [comment]
I will do this with #475
