### ISSUE TITLE
Rename `ResultAnalyser` -> `MeasurementResultAnalyser`

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#457]
… to be more specific

**Comment by RomanLangrehr** [comment]
lgtm

**Comment by jGleitz** [comment]
Other thoughts?

**Comment by flyfl** [comment]
There are no similar classes that have a ResultAnalyser functionality (`FinalJudge` is obviously doing something else). It is more specific, but I'm not sure if we need that.

**Comment by acBerger** [comment]
I like the idea of being more specific. Even if we do not need it yet we agreed on meaningful and specific names.
