### ISSUE TITLE
Javadoc Acronyms

### ISSUE THREAD

**Issue by viridispirus** [Beagle-PSE/Beagle#458]
How we decide which acronyms are allowed and which one not? We discussed this in one meeting but we still haven't a clear solution for this. I would propose that words (names) which in our SRS are acronyms are allowed.

**Comment by RomanLangrehr** [comment]
That's a relly good idea. Especially because we have all those acronyms defined.

**Comment by jGleitz** [comment]
I like this idea, too. We may introduce a more sophisticated system with #459 if we're bored.

**Comment by m1cm1c** [comment]
Please be aware that this will change `getRDIAsToBeMeasured()` to `getResourceDemandingInternalActionsToBeMeasured()`.

**Comment by RomanLangrehr** [comment]
> Please be aware that this will change `getRDIAsToBeMeasured()` to `getResourceDemandingInternalActionsToBeMeasured()`.

Then we should probably add some acronyms.

**Comment by m1cm1c** [comment]
> Then we should probably add some acronyms.

It doesn't even appear written out in full in the SRS.

**Comment by jGleitz** [comment]
This is why creating an acronym page for Javadoc would be the cleaner solution.

**Comment by jGleitz** [comment]
On the other hand: Do we need Acronyms that bad? We could just decide to leave them out and get used to long method names.

**Comment by m1cm1c** [comment]
So `reportMeasurementResultFor(final ServiceEffectSpecificationLoop serviceEffectSpecificationLoop, final LoopRepetitionCountMeasurementResult result)` ... I'm in favor of keeping "seff" as an acronym.

**Comment by flyfl** [comment]
Noooo. Please let us stick to those acronyms and if necessary, keep them documented anywhere else.

**Comment by acBerger** [comment]
All used Acronyms have to be in the glossary.

**Comment by acBerger** [comment]
Blocked by #466.

**Comment by acBerger** [comment]
Sorry, this is nonsense as we use the existing glossary document.
