### ISSUE TITLE
Drop Papyrus and Redo all Diagrams in Umlet

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#472]
This is decided. Progress:
 * [ ] Beagle Core
 * [ ] Expressions
 * [x] Package
 * [ ] Controllers
 * [ ] Sequence

In the moment, each Pull Request seems to break some part of some diagram.

With Umlet, we get: 
 * Automatic building **and testing** of diagrams
 * Qualified assosiations
 * A file format that is better readable and can thus better be merged by hand.
 * Elements that don’t move around randomly

I liked Papyrus for its approach but I think that its bugs are heavily holding us back. I think we could redo the diagrams in a collective effort tonight.

**Comment by acBerger** [comment]
I did not read anything but the title but I agree!

**Comment by acBerger** [comment]
For me it seems like the diagrams break down even when there were no changes. This cannot last as it is.

**Comment by acBerger** [comment]
Closed as there are issues for every diagram
