### ISSUE TITLE
Redraw Package Diagram in UMLet

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#477]

**Comment by acBerger** [comment]
I first started doing package diagrams like this:
![p1](https://cloud.githubusercontent.com/assets/10773356/12207922/c6be34be-b649-11e5-8123-ab9cee5d6fd9.png)

But it seems like Umlet wants to do them like this:

![p2](https://cloud.githubusercontent.com/assets/10773356/12207927/c99e8468-b649-11e5-8f1c-b0c4d4f64f9d.png)

What do you prefer? I was not able to find out which one is right yet. Probably they are both okay.

**Comment by jGleitz** [comment]
I only found images using the second one. And it’s not that bad after all.

**Comment by acBerger** [comment]
I think the first looks way better, but on the other hand the second one is easier and faster to create.
