### ISSUE TITLE
UML Software

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#50]
We should decide on a software to create UML diagrams.

The software should:
- Export the diagram as .pdf
- Export class diagrams to Java Class Stubs. (We can use a different software for other UML diagrams, but I don't know if it's a good idea to do so.)

**Comment by jGleitz** [comment]
It would be nice to have this as an Eclipse plugin. But this is not mandatory.

**Comment by acBerger** [comment]
### Eclipse Plugins for creating UML Diagrams

- [papyrus] (https://eclipse.org/papyrus/)
- [UML-Designer] (https://marketplace.eclipse.org/content/uml-designer) implements Package Hierarchy, Class Diagam, Component Diagram, Composite Structure Diagram, Deployment Diagram, Use Case Diagram, Activity Diagram, State Machine, Sequence Diagram and  Profile Diagram
- [UMLet] (https://marketplace.eclipse.org/content/umlet-uml-tool-fast-uml-diagrams) UML Tool for Fast UML Diagrams
- [ObjectAid UML Explorer] (https://marketplace.eclipse.org/content/objectaid-uml-explorer) for creation of class and sequence diagrams *(from existing code?) --> not that useful for us?*
- [UML Lab Modeling IDE] (https://marketplace.eclipse.org/content/uml-lab-modeling-ide) to seamlessly combine modeling and programming *they say you should import your software project and we don't have code yet so this is probably not the right tool*
- [UML 2 Plugin for Eclipse] (https://marketplace.eclipse.org/content/uml-2-plugin-eclipse) *seems to be a rather simple tool*
- [ModelGoon UML4Java] (https://marketplace.eclipse.org/content/modelgoon-uml4java) provides: package dependency, class, interaction and sequence diagram (uses selected classes to create them)
- [Topcased UML Editor] (https://marketplace.eclipse.org/content/topcased-uml-editor) supports: Package, Class, Object, Component, Deployment, Use Case, Sequence, Activity, State Machine, Composite Structure
- [TextUML Toolkit] (https://marketplace.eclipse.org/content/textuml-toolkit)

and more (I just looked for a few). Does anyone already know one of these of another?
If possible I would like to have one for all types of models, so we should check for this.

I tried to get a idea of these by only reading through the intro, so please correct me if I am wrong with my suggestions.

**Comment by acBerger** [comment]
@jGleitz installed papyrus before and is not very happy with it

**Comment by jGleitz** [comment]
Does somebody have a change to look into this? Is quite important to decide for a good tool soon.

@acBerger is already looking into it, but she could really need some support.

**Comment by jGleitz** [comment]
@RomanLangrehr, @m1cm1c being the most technically experienced, could you look into this please? 

A optimal solution would be a software, that:
 1. allows source code generation from UML
 2. produces a file format that can be rendered using command line tools
 3. is an Eclipse plugin.

**Comment by jGleitz** [comment]
I think the importance of the points is 2., 1., 3.

**Comment by jGleitz** [comment]
@RomanLangrehr have you already decided?

**Comment by RomanLangrehr** [comment]
Yes, we will use [UML-Designer](https://marketplace.eclipse.org/content/uml-designer).
Installation instructions will follow.

**Comment by jGleitz** [comment]
> 
Avoid this tool!
>
Submitted by Robert Cancilla on August 19, 2015 - 21:59
>
Horrible resolution on my 23 inch iMac, horrible UI totally unfriendly and that was only on the most basic class diagram!
- See more at: https://marketplace.eclipse.org/content/uml-designer#sthash.Vaob1L29.dpuf

I generally trust your decision and I think that all software suffers under the fact that you only comment if you don’t like it. But have you checked whether there is truth in the overall negative comments on the project page?

**Comment by RomanLangrehr** [comment]
The resolution is OK. It just doesn't export everything as vector graphics, so when you print your diagrams to large, they get pixelated.
I didn't tried the class diagram yet, because we don't need it for the SRS.

**Comment by RomanLangrehr** [comment]
Actually I just found out that [UMLet] (https://marketplace.eclipse.org/content/umlet-uml-tool-fast-uml-diagrams)  is quite powerfull. It also supports point 1, but not 2.

**Comment by jGleitz** [comment]
Okay. So I take it you need some more time for investigation?

**Comment by RomanLangrehr** [comment]
No, I think that tool is finally pretty good.

**Comment by m1cm1c** [comment]
There is something I noticed about this tool: It generates SVG files which are displayed and converted by some software incorrectly when demanding high resolutions (or when zooming in). Fortunately, Inkscape isn't one of these applications. So maybe be careful and check whether what's shown actually is what you drew.

**Comment by jGleitz** [comment]
fixed by #98
