### ISSUE TITLE
Create a de.uka.ipd.sdq.beagle.api package

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#500]
Containing all types available to classes using extension points.

This communicates our API much clearer (because you see what you are supposed to use) but may lead to some unexpected placements.

**Comment by RomanLangrehr** [comment]
This package would contain all classes that are in an extension point.
I don't like it, because the extension points already define, which classes should be used.

**Comment by jGleitz** [comment]
>  I don't like it, because the extension points already define, which classes should be used.

Not really. There are further classes that will be used by Analysers (e.g. `SEFF Loop`), but others should not be used (e.g. `Final Judge`). We do not communicate that anyhow.

Athough, when separating like that, more types would go to the API packages than into the Core package.

**Comment by RomanLangrehr** [comment]
But I think that's clear, too: Every classes you get by calling methods, you can use.
I don't think the api package is necassary.
