### ISSUE TITLE
Design Document: Create SRS Chapter

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#501]
* For each required criterion, functional requirement and non-functional requirement, explain how our design reflects it and enables Beagle to fulfil it.
 * Where applicable, to the same for optional criteria, functional requiremento and non-functional requirements
 * Explain changes to the SRS

**Comment by flyfl** [comment]
>For each required criterion, functional requirement and non-functional requirement, explain how our design reflects it and enables Beagle to fulfil it.

I agree that we should check, if each mandatory criteria is fulfiled. But I think it is not nessecary to have each criterion explicitly mentioned.

>Explain changes to the SRS

Do we have any more changes than the CTA?

**Comment by jGleitz** [comment]
> I agree that we should check, if each mandatory criteria is fulfiled. But I think it is not nessecary to have each criterion explicitly mentioned.

Why not? If we managed to get everything covered, that’s a good thing and I think we should point it out

**Comment by flyfl** [comment]
First, I think that could get too detailed, some explanations could repeat several times. Second, that may take a lot of time. Maybe we just want to state out what has changed (and saying that we have implemented the rest of mandatory criteria).

**Comment by RomanLangrehr** [comment]
> First, I think that could get too detailed, some explanations could repeat several times. Second, that may take a lot of time. Maybe we just want to state out what has changed (and saying that we have implemented the rest of mandatory criteria).

I agree. We should first document and explain all of our design decisions.
