### ISSUE TITLE
[IP #040] SEFF classes

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#571]
Implement SEFFLoop, SEFFBranch,
ResourceDemandingInternalAction ExternalCallParameter.

And classes that directly belong to them like CodeSection.

**Comment by RomanLangrehr** [comment]
Implementation is done.

**Comment by acBerger** [comment]
You said you implemented all, I think you missed `ExternalCallParameter`.

**Comment by acBerger** [comment]
I am still on this tests, as it took much longer as expected. Fortunately there should be a working version soon, but I am going to wait for #600 .

**Comment by RomanLangrehr** [comment]
> You said you implemented all, I think you missed `ExternalCallParameter`.

Done.

**Comment by acBerger** [comment]
I added the tests.

**Comment by jGleitz** [comment]
> I added the tests.
> RomanLangrehr added needs review and removed ready labels 3 minutes ago

Please note that a lot of the tests are failing!

**Comment by RomanLangrehr** [comment]
> Please note that a lot of the tests are failing!

Ops.

**Comment by RomanLangrehr** [comment]
@acBerger 
I think some files are missing...
![image](https://cloud.githubusercontent.com/assets/10776736/12380451/831bf896-bd73-11e5-932d-0909e48f55c2.png)

**Comment by acBerger** [comment]
Yes, this does not work in eclipse as I could not find a possibility for
the file path. You have to run gradle. Sorry.
Am 17.01.2016 23:39 schrieb "Roman Langrehr" <notifications@github.com>:

**Comment by jGleitz** [comment]
This would likely be fixed by #291.

**Comment by RomanLangrehr** [comment]
I have fixed my code *and* the test cases.

The remaining test cases don't fulfill the method's contract. As the SeffClasses are not part of our API, we don't need to asure defensive programming. They should be removed.

**Comment by jGleitz** [comment]
> As the SeffClasses are not part of our API, we don't need to asure defensive programming.

This is an interesting point. I see your argumentation and generally agree with it. But in `CodeSection`’s constructor for example, you *do* argument checking. And I think it totally makes sense there. And if the code exists, it must be tested.

I strongly think that we need to be consistent on this matter. And on the other hand, defensive programming and tests may likely improve the code’s quality (no “silent” errors).

**Comment by acBerger** [comment]
As we decided to do defensive programming I thought that we will do it for all code, not only the one of our API. That is why I tried to do so.
So you prefer to assume that the input is right?
