### ISSUE TITLE
[IP #050] PCM Repository loader

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#572]
Create a class that provides all information from the PCM which are
relevant for Beagle and a factory that uses these information to create
the SEFFLoops, SEFFBranches, ResourceDemandingInternalActions
and ExternalCallParameters.

Depends partly on IP#040 ( #571 ) (SEFF classes).

**Comment by flyfl** [comment]
Implementation done. Attention! The PcmBlackboardFactory depends on the naming of entities within
the repository-file, because I could not solve how to access the SourceCodeDecorator.

**Comment by m1cm1c** [comment]
The tests fail because the constructor of `PcmRepositoryBlackboardFactory` throws `ClassNotFoundException`s.

**Comment by flyfl** [comment]
>The tests fail because the constructor of PcmRepositoryBlackboardFactory throws ClassNotFoundExceptions.

Done.

**Comment by m1cm1c** [comment]
Not done.
> @throws IllegalClassFormatException If input parameter does not represent a valid repository file.

is not appropriate behaviour. We decided to use defensive programming which means that you can't do what you want if you receive bullshit arguments. If you receive bullshit arguments, you throw an IllegalArgumentException.

An IllegalClassFormatException is
> Thrown by an implementation of ClassFileTransformer.transform when its input parameters are invalid. This may occur either because the initial class file bytes were invalid or a previously applied transform corrupted the bytes.

([source](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/IllegalClassFormatException.html))

**Comment by flyfl** [comment]
That must haven happend when you force pushed into this branch.

**Comment by m1cm1c** [comment]
I only removed a single commit (I previously made) affecting only the tests.

Throwing FileNotFoundExceptions at `getBlackboardForIds` is against the fail early principle. Please already fail when it is attempted to create an object which operates on a nonexistent file.

**Comment by flyfl** [comment]
>Throwing FileNotFoundExceptions at getBlackboardForIds is against the fail early principle. Please already fail when it is attempted to create an object which operates on a nonexistent file.

Problem: During instanciation of a repository, this class can not know if the mapping to a giving sourceCode file does exist or not. This should actually cause a FileNotFoundException in the SourceCodeDecorator. And the repository loader is not obligated to manage such an exception.

**Comment by m1cm1c** [comment]
You're still using the wrong kind of exceptions.
