### ISSUE TITLE
[IP #060] Blackboard

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#573]
Implement Blackboard.

(Not depending on IP#050 ( #572 ), as the Blackboard only needs the class stubs
for SEFFLoop, SEFFBranch, ResourceDemandingInternalAction,
ExternalCallParameter and the
ParameterisationDependentMeasurementResult subclasses and not
their functionality).

**Comment by viridispirus** [comment]
Is that a wrong Set? It is in all views.

![mistake](https://cloud.githubusercontent.com/assets/10431811/12373010/043a315e-bc6b-11e5-9aba-8036665d958e.PNG)

**Comment by jGleitz** [comment]
> Is that a wrong Set? It is in all views.

Oh yes, it is. This is **very** wrong!

**Comment by viridispirus** [comment]
Ok, I thougt so but was not sure because its in all views. Thanks.

**Comment by viridispirus** [comment]
Stupid Question: The `AnalysisController` creates the blackboard, right? How did the views get this one? Is there a getter method still missing?

**Comment by jGleitz** [comment]
The Views are created by `AnalysisController` and take their `Blackboard` in their constructors. Note that there must not be a getter or setter for the `Blackboard`!

**Comment by viridispirus** [comment]
Ok.

**Comment by viridispirus** [comment]
I don't know implement the this two method here. Please help me.

![blackboardstorer](https://cloud.githubusercontent.com/assets/10431811/12376651/c07dd908-bcff-11e5-80dc-7b548e119d86.PNG)

**Comment by jGleitz** [comment]
> I don't know implement the this two method here. Please help me.

I’m guilty for them, so if you push your work into a feature branch, I can contribute them.

Side note: You obviously have encoding issues, please google how to set up your Eclipse to exlusively use UTF-8.

**Comment by viridispirus** [comment]
Oh ok. Thanks.

**Comment by flyfl** [comment]
Written all tests. I guess that some more are necessary, but I can't imagine more for now.
Could someone scan the current BlackboardBranch and mention mistakes or suggestions?

**Comment by flyfl** [comment]
#598
