### ISSUE TITLE
[IP #070] Blackboard Views

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#574]
Implement Read-Only Measurement Controller Blackboard View,
Measurement Controller Blackboard View,
Read-Only Measurement Result Analyser Blackboard View,
Measurement Result Analyser Blackboard View,
Read-Only Proposed Expression Analyser Blackboard View,
Proposed Expression Analyser Blackboard View.

–
(Not depending on IP#060 ( #573 ), as the Blackboard Views only need the
blackboards method stubs.)

**Comment by viridispirus** [comment]
I am nearly finished this issue.
I have in this method two questions:
  1. What I have to implement here?
  2. Can I rename the method to solve checkstyle error or did checkstiye fail here?

![problem](https://cloud.githubusercontent.com/assets/10431811/12373533/38980686-bc7c-11e5-8f6b-1e073b357e7c.PNG)

Checkstyle said here: 
`Method type name 'WRITTEN_TYPE' must match pattern '(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)'.`

**Comment by jGleitz** [comment]
> `Method type name 'WRITTEN_TYPE' must match pattern '(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)'.`

Who adapted the checkstyle Regex? This was once correct!

**Comment by viridispirus** [comment]
Ok, this checkstyle error is the last thing to do for this issue. Shall I fix the checkstyle rule or is it better when  @acBerger did that?

**Comment by acBerger** [comment]
Independenly from who is fixing it, the fix should be done as PR to the master (as other may depend on it and we do not know in which order we get the branches in). So an extra issue would be great.

**Comment by flyfl** [comment]
Done. Everything should work. Travis fail because of
>ocumentation:designUmlException in thread "main" java.lang.RuntimeException: Cannot make dir /home/travis/UMLet

**Comment by RomanLangrehr** [comment]
That's no problem. I restarted the build.
