### ISSUE TITLE
[IP #095] Make gradle build eclipse projects.

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#578]
Automatically resolve dependencies in `MANIFEST.MF`.

**Comment by jGleitz** [comment]
Update: I can build code that uses the Eclipse API. 

Using libraries that are defined in MANIFEST.MF but not available in the default Eclipse installation (like Apache Commons) is not yet possible. I have not quite understood the mechanisms in the Eclipse API yet.
