### ISSUE TITLE
Use Apache Commons Validator

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#583]
We decided to perform defensive programming on all our methods, a decision I highly support. I think checking every parameter thoroughly will improve our API’s quality highly.

However, nobody likes to write those same lame `if`s. They are boring, dumb and take up space. So I propose to use [Apache Common’s Validator](https://commons.apache.org/proper/commons-validator/) ([Javadoc](https://commons.apache.org/proper/commons-validator/javadocs/api-1.5.0/)).

Its checking methods are *short* and *highly readable*.

**Comment by jGleitz** [comment]
Sorry, I posted the wrong link. This is the correct one: https://commons.apache.org/proper/commons-lang/javadocs/api-release/index.html

**Comment by acBerger** [comment]
As no one seems to have problems with @jGleitz's suggestion and we already started using it I think this is decided.
