### ISSUE TITLE
[Checkstyle] Whitespace Shit Again ...

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#584]
![](http://i.imgur.com/QChwBdG.png)

I thought we got rid of this.

**Comment by jGleitz** [comment]
I can’t reproduce, on my machine (in the `Core` project), both Formatter and Checkstyle settle for the same solution

![array-works](https://cloud.githubusercontent.com/assets/4305652/12287324/fd042378-b9cb-11e5-8c02-a87e54344d0b.png)

**Comment by m1cm1c** [comment]
Sorry, I only checked the global settings, not the project-specific settings. The project wasn't using the default formatter (which I set accordingly) but set its own.
