### ISSUE TITLE
[Checkstyle] Final for Everything

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#585]
So I start writing the doc for the GUI because I have to in order to have the slightest chance of finishing in time which I probably won't and then start implementing immediately afterwards because I feel like first documenting everything will consume too much time even though it's what actually should be dond. So to do at least this neatly, I use variables which is a common thing to do if you write code (just in case you haven't noticed). Then **BAM**

![](http://i.imgur.com/a4kicTs.png)

What the actual fuck is this!? Why would I have the slightest interest in making every single variable I'm ever going to use **in a method** final which would render them entirely useless!?

**Comment by jGleitz** [comment]
No need for getting aggressive. If you want to put new things in the variable, just do so, and the warning should go away. If you don't, just leave the `final` because in that case, it's supposed to be there.

**Comment by jGleitz** [comment]
On my machine, it’s working exactly as expected:


![just-one-value](https://cloud.githubusercontent.com/assets/4305652/12287258/6f404116-b9cb-11e5-8e31-ab4ccc62b253.png)

![another-value](https://cloud.githubusercontent.com/assets/4305652/12287260/741a0cb2-b9cb-11e5-927b-30281a5c71d5.png)
