### ISSUE TITLE
Convention Constants for Resource Types

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#586]
In the moment, the conventional values for resource types are defined in `Resource Demanding Internal Action`. @RomanLangrehr put them into constants for IP #040 (#571). I generally like the idea of putting these values into constants. But these values are also used in contexts where the class `Resource Demanding Internal Action` has no meaning. Namely the context of `Measurement Tool`s. I’d find it irritating to have a dependency from them to this class (as the design avoids exactly that).

I propose to either define them in their own class or to put the definitions in their own html file we can link to from different classes.

**Comment by RomanLangrehr** [comment]
I thought about a creating a class ResourceType.
This class would have a string, the type and a boolean `isMs`, which can be set when the measurement is in ms.

**Comment by jGleitz** [comment]
> I thought about a creating a class ResourceType.

Well maybe this is the most elegant solution. We could still offer the usual types as constants. And I guess a flyweight would make sense.

**Comment by RomanLangrehr** [comment]
> We could still offer the usual types as constants. 

Yes, that was my intention.

**Comment by jGleitz** [comment]
> Yes, that was my intention.

:+1:

**Comment by RomanLangrehr** [comment]
Implementation done.

**Comment by RomanLangrehr** [comment]
This will be tested with ip40
