### ISSUE TITLE
[Checkstyle] Import Separation

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#604]
Formatter vs. Checkstyle
![](http://i.imgur.com/fjpvraR.png)

See `de.uka.ipd.sdq.beagle.gui.handlers.DemoBeagleContextMenuEntryHandlerForRepositories` in [https://github.com/Beagle-PSE/Beagle/tree/ip-030-gui](https://github.com/Beagle-PSE/Beagle/tree/ip-030-gui).

**Comment by jGleitz** [comment]
This is invalid. The bug occurred because the wrong import order was set on the GUI project. I pushed a fix.
