### ISSUE TITLE
[IP #120] Implement Measurement Results

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#609]
Implement ParameterisationDependentMeasurementResult and all
of its subclasses. (Package “Measurement”)

**Comment by RomanLangrehr** [comment]
Implementation is done.

**Comment by acBerger** [comment]
Are you aware that there is still a TODO in `BranchDecisionMeasurementResult`? Please solve that if it was only a note to you or open an issue for it.

**Comment by RomanLangrehr** [comment]
> Are you aware that there is still a TODO in BranchDecisionMeasurementResult? Please solve that if it was only a note to you or open an issue for it.

Thanks, I removed it. This was already resolved.

**Comment by jGleitz** [comment]
@RomanLangrehr: Can you please explain your intentions regarding the implementation of `equals`?

I don’t know if we even need to implement it, but making results with the same parameterisation equal, regardless of the result’s value, doesn’t sound right to me.

**Comment by RomanLangrehr** [comment]
@jGleitz I forgot to implement `equals` in the subclasses. Sorry.

I think we need them, because we store them in sets, don't we?

**Comment by jGleitz** [comment]
> I think we need them, because we store them in sets, don't we?

We do, but isn’t “equals ⇔ same instance” enough for them?

**Comment by acBerger** [comment]
I implemented all of the test but the one for equals does not work yet as it is not possible to mock `equals`with mockito. I have to find another possibility for the parameterisation.

**Comment by acBerger** [comment]
I found a possibilty to solve my problem with equals.
Some of the test are failing, please check your code.

**Comment by RomanLangrehr** [comment]
@acBerger I removed the equals/hashCode methods. I think the test case has to be changed a little bit for that.
