### ISSUE TITLE
Citation System

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#61]
A convenient way to manage citation sources and include citations must be found. LyX likely already has support for this.

**Comment by m1cm1c** [comment]
I like [this one](http://tim.thorpeallen.net/Courses/Reference/Citations.html).

**Comment by jGleitz** [comment]
Oh, I realise the caption is ambiguous. I was thinking of a technical solution. Nevertheless, the system (as in "how to write citations") is important, too. So why not discuss both here ;)

**Comment by m1cm1c** [comment]
Oops. Yeah, let's discuss both here.

I don't like the style of `quotation`. Additional indentation for the first line is just ugly. The style of `quote` is much better.

@jGleitz: Do you aim to have some kind of linking implemented? If so, please explain.

**Comment by RomanLangrehr** [comment]
> I was thinking of a technical solution.

Is there any alternative to BibTeX ?

**Comment by jGleitz** [comment]
> Is there any alternative to BibTeX ?

I never used any bibliography tool with LaTeX. If you have experience in it and want to set it up (I really think LyX has GUI support for it), take the ticket!

**Comment by jGleitz** [comment]
> Do you aim to have some kind of linking implemented? If so, please explain.

Yes I do. As always with LaTeX, we’ll do it the proper way: Keep a list of literature and insert a link to it. This way, we can always adapt our citation style or a source’s metadata at a later point, without going through the whole document again.

**Comment by jGleitz** [comment]
> I don't like the style of quotation. Additional indentation for the first line is just ugly. The style of quote is much better.

You have to realise that you only apply __markup__ in LyX. So please use quote and quotation as described in the user manual. Styling can be adapted at any later point.

**Comment by RomanLangrehr** [comment]
Are there any citations in the requirement specification right now? (For testing purpose)

**Comment by acBerger** [comment]
I don't think so.

**Comment by jGleitz** [comment]
@m1cm1c: Do you have something?

**Comment by RomanLangrehr** [comment]
We still have to decide on the citation stile. The stile must be available as .bst file (You don't want to create your own...).
The current stile is "plain". What i don't like about it: It uses only numbers as refernce, so you use [1], [2], etc to cite.
I just looked for some citation styles and I liked best "apalike", which based on the common citation standard "APA". It is similar to @m1cm1c 's one.

**Comment by jGleitz** [comment]
I did not look up all your references. But if we can get something like `[author year]` and maybe sometimes `[author year pages]` for referencing, I’m happy.

The declaration style in the Bibliography that comes with #70 is fine for me.

**Comment by m1cm1c** [comment]
A part of the definition of `Palladio Component Model` is a citation from the second set of slides (page 33).

**Comment by RomanLangrehr** [comment]
> I did not look up all your references. But if we can get something like [author year] and maybe sometimes [author year pages] for referencing, I’m happy.

In the style i proposed you cite like [Author year]. Pages can be added anyway when citing.

**Comment by jGleitz** [comment]
@m1cm1c we cannot cite the lecture!

**Comment by m1cm1c** [comment]
Why not?

**Comment by jGleitz** [comment]
> Why not?

It is not available to the public.

**Comment by m1cm1c** [comment]
True for some parts, but he might just have copied it from [some website of a different university](https://www.tu-chemnitz.de/informatik/ST/research/projects/palladio-component-model) without declaring to have done so. Some other parts might just be [available on Wikipedia](https://en.wikipedia.org/wiki/Conway's_law) citing [some other website](http://www.melconway.com/Home/Conways_Law.html). But yes, if the slides aren't available to the public, we shouldn't use them as a source (which they probably aren't anyway).

**Comment by jGleitz** [comment]
I noticed that Prof. Reussner didn’t cite his statements most of the times. But I think this is okay to some degree, because it’s a lecture. 

If you can find the primary sources, its best to use them. If they are written instead of websites, even better!

**Comment by jGleitz** [comment]
@m1cm1c: Are you okay with the proposed citation system?

**Comment by m1cm1c** [comment]
Yes.

**Comment by jGleitz** [comment]
fully implemented by #108
