### ISSUE TITLE
[IP #130] Implement Blackboard Controllers

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#611]
Description/Classes: Implement BeagleController and MeasurementController.

Depends on: IP#060 (Blackboard) ( #573 ) and IP#070 (Blackboard Views) ( #574 )

**Comment by acBerger** [comment]
Did you mean AnalysisController or BeagleController?

**Comment by RomanLangrehr** [comment]
I'll write test for them.

**Comment by m1cm1c** [comment]
I think that everything that can currently be done is in `ip-130-measurement-controller-analysis-controller`. I'll correct the constructors once https://github.com/Beagle-PSE/Beagle/pull/599 compiles.

This issue depends on #650 which itself depends on #598. Once I adapted the constructors, #599 will have to get merged first.

**Comment by m1cm1c** [comment]
I forgot to mention that this also depends on #661.

**Comment by RomanLangrehr** [comment]
Tests have been finished.
