### ISSUE TITLE
Naming Convention for Methods in Test Classes

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#637]
Currently we use `testMethodName` as names in the tests (mainly because they are generated). @jGleitz suggested to use `methodName` as this is easier to read if you have a list of all test methods.
As all test methods are in a Test class it is not needed to write 'test' before the name.

Are there any other perferences?

I agree with @jGleitz that it is better to use the simple name, even through this means we have to adapt the names generated by JUnit.

**Comment by jGleitz** [comment]
Any thoughts on this? Because otherwise, I’d take this as decided.

**Comment by viridispirus** [comment]
I agree too.
