### ISSUE TITLE
Proposition: It Is Not Possible to Create an EvaEx that Contains Itself

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#638]
Given that the client only uses the API, he can never create such a case.

Can you confirm?

**Comment by m1cm1c** [comment]
This is a useful restriction, not only from a usage perspective. Otherwise evaluation would be somewhere between really difficult for a few cases and impossible for general cases without further restrictions.

**Comment by jGleitz** [comment]
The design contains an `ExpressionRecursionException` for that case. But I think we can remove it, as it’s simply not possible to construct such a case.

**Comment by m1cm1c** [comment]
Oh, that's what you're talking about. Yes, of course such a case isn't possible and the exception should be deleted.

**Comment by flyfl** [comment]
Agreed, why would we like to do this? That would be an endless recursion...

**Comment by jGleitz** [comment]
> why would we like to do this?

This is not about whether we *want* to do this. It’s obvious that we don’t. This issue is about **whether it is technically possible** to build a recursive expression. Because I think it isn’t.

**Comment by m1cm1c** [comment]
Our design involves a flyweight pattern and immutability making it definitely impossible for an evaex to contain itself.

**Comment by jGleitz** [comment]
I removed the exception.
