### ISSUE TITLE
[IP #140] Kieker measurement tool

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#639]
Build a MeasurementTool executing Kieker.

Dpends on:
IP#120 ( #609  )(Measurement Results), IP#060 ( #573 ) (Blackboard), IP#070 ( #574 ) (Blackboard
Views), IP#040 ( #571 ) (SEFF classes) and IP#125 ( #610 ) (Measurement Order)

**Comment by RomanLangrehr** [comment]
@acBerger Will start writing the tests.

**Comment by jGleitz** [comment]
This is tested by manually
