### ISSUE TITLE
[IP #150] Averaging Measurement Result Analyser

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#640]
Build a Measurement Result Analyser, which takes as
EvaluableExpression a ConstantExpression for all
MeasurableSeffElements with the average of all available
measurement results. And the  tool helper classes. (AbstractXXX)

Depends on: IP#120 ( #609 ) (Measurement Results), IP#060 ( #573 ) (Blackboard), IP#070 ( #574 ) (BlackboardViews), IP#040 ( #571 ) (SEFF classes)

**Comment by acBerger** [comment]
I can test this.
