### ISSUE TITLE
[IP #160] Implement Evaluable Expression Fitness Function

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#641]
Implement a EvaluableExpessionFitnessFunction.

Depends on: IP#120 ( #609 ) (Measurement Results) and IP#040 ( #571 ) (SEFF classes)

**Comment by acBerger** [comment]
It is only `AbstractionAndPrecisionFitnessFunction` to test isn't it?
Is the implementation finished?

**Comment by acBerger** [comment]
oh, I forgot to mention it here: I am testing this.

**Comment by acBerger** [comment]
@m1cm1c Please check your Implementation as the tests fail.

**Comment by m1cm1c** [comment]
I fixed the bug.
