### ISSUE TITLE
User Configuration

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#644]
#607 showed that we need to think a little more about the API of the `User Configuration`. I’m not sure if the GUI collects enough information in the moment. Especially @m1cm1c and @flyfl should help to answer these questions:

 * Which information is required to write results back to the repository?
 * Is it sufficient to store the EMF Elements?
 * Do EMF Elements point to the file they came from?
 * Can EMF Elements be serialised?
 * Are there advantages in storing IDs?

Furthermore, I think that the user configuration should contain the raw data of what the user configured. It will contain user settings in the future, so I propose to put it on the Blackboard. (We could for example store settings for the final judge or about measurement precision in it).

**Comment by flyfl** [comment]
>Which information is required to write results back to the repository?

The same as it is needed to load -> `path of the repository file`

>Is it sufficient to store the EMF Elements?

The composition of the repository will never change, just some annotations will be made. From my point of view, that should be enough.

>Do EMF Elements point to the file they came from?

Yes. There are some commands like "predecessor" and "succesor" or even more specified ones if you handle concrete types.

>Can EMF Elements be serialised?

Sorry, I don't know.

>Are there advantages in storing IDs?

If we don't want to keep the EMF Elements during analysis, yes.

**Comment by jGleitz** [comment]
Hm. I propose to store a `Map<File, Set<String>>` on the user configuration. The `File` refers to a repository file, the `Set` to a set of IDs that shall be measured. If the `Set` is `null`, all elements shall be measured. 

What do you think?

**Comment by RomanLangrehr** [comment]
> What do you think?

Sounds good.

**Comment by jGleitz** [comment]
So as far as no one disagrees, this is decided.

**Comment by flyfl** [comment]
Why do you want to map several Files to a set of IDs? I think we are working just on one repository file. Am I wrong?

**Comment by jGleitz** [comment]
> I think we are working just on one repository file.

I don’t know.

 * I can’t think of a use case for it
 * But I also think that it does not make the implementation any harder, so I don’t see a reason for not doing it, either.

**Comment by RomanLangrehr** [comment]
We decided to allow only one file.

**Comment by jGleitz** [comment]
As discussed today, the `UserConfiguration` needs a field for the Eclipse Project that is being operated on, which will be set by the GUI (because it’s not possible to determine that at a later point).
