### ISSUE TITLE
Hyperreff jumps not at exact place

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#65]
As I tested @jGleitz' Pull request for the Hyperreffs in SRS I discovered that when clicking on one it jumps a little bit below. To read the point you wanted, you have to scroll up most of the times.
This is not as wanted.

![crossreverence](https://cloud.githubusercontent.com/assets/10773356/11323146/c4aeb018-910a-11e5-9ceb-3f7e22483f96.png)
*I clicked at /A40/ in the picture and did not scroll afterwards.*

Is this a bug in my document reader or occurs this for you too?

**Comment by jGleitz** [comment]
Can anybody reproduce this with a reader that’s not Envince? (I also have it with Envince, the Reader always jumps on line below the line it should jump to).

**Comment by RomanLangrehr** [comment]
Yes, it's the same with FoxitReader

**Comment by RomanLangrehr** [comment]
Some links in the TOC also jump to the wrong page. (The last entrys: List of figures, Bibliography)

**Comment by jGleitz** [comment]
For the TOC issues:

```
Class scrbook Warning: \float@addtolists detected!
(scrbook)              Implementation of \float@addtolist became
(scrbook)              deprecated in KOMA-Script v3.01 2008/11/14 and
(scrbook)              has been replaced by more several more flexible
(scrbook)              features of package `tocbasic`.
(scrbook)              Since Version 3.12 support for deprecated
(scrbook)              \float@addtolist interface has been
(scrbook)              restricted to only some of the KOMA-Script
(scrbook)              features and been removed from others.
(scrbook)              Loading of package `scrhack' may help to
(scrbook)              avoid this warning, if you are using a
(scrbook)              a package that still implements the
(scrbook)              deprecated \float@addtolist interface .
```
