### ISSUE TITLE
Create Fail API

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#656]
We are encountering more and more situations in which we see a potential situation (illogical data, Exceptions thrown, etc.) where we just don’t know how to continue. Usually, we’re “rage quitting” by throwing a `RuntimeException`.

But this may often not be the best solution. I propose to create an API to which a client can go to and tell it “I don’t know how to continue”. In its firs implementation, the API will just throw an Exception. But this would enable the GUI at a later point to present a message to the user. 

The client would also enabled to provide code that contiues the analysis or “tries again”. So unlike when throwing an Exception, we’re giving the user the chance to fix the issue and to continue the analysis.

I’ll code an example to visualise what I mean.

**Comment by RomanLangrehr** [comment]
I think this makes only sense in some parts.

Thinks like `NullPointerException`s or `IllegalArgumentException`s should never be thrown in any use case, so we don't need such an API for that.

**Comment by jGleitz** [comment]
> Thinks like NullPointerExceptions or IllegalArgumentExceptions should never be thrown in any use case, so we don't need such an API for that.

Absolutely. 

I was thinking of cases like
 * The user provides non-compilable source code
 * Launching a run configuration fails
 * The user kills the measurement thread
etc. pp.

At such points, throwing an exception will destroy all progress.

**Comment by flyfl** [comment]
I don't think we need to handle any of this issues. The user is indepted to offer compilable source code and should not kill the measurement thread...

**Comment by jGleitz** [comment]
> I don't think we need to handle any of this issues. The user is indepted to offer compilable source code and should not kill the measurement thread...

Well, if something like this happens, you’ll usually have code to catch it anyway (validation functions, `catch` blocks, etc.). So you already have to do *something* about it. Why not reporting the error properly?

**Comment by jGleitz** [comment]
I pushed my ideas to `fail-api`. I’d like to hear your thought about it!

Usage example:

In `EclipseLaunchConfigurationLaunchConfiguration`, @RomanLangrehr already has this code:

```java
try {
	this.launchConfiguration.launch(ILaunchManager.RUN_MODE, null);
} catch (final CoreException exception) {
	throw new RuntimeException(exception);
}
```

if he adds this to his class: 

```java
private static final FailureHandler FAILURE_HANDLER = FailureHandler.getHandler("Eclipse Run Configuration Launcher");
```

he can replace his code with:

```java
public void execute() {
	try {
		this.launchConfiguration.launch(ILaunchManager.RUN_MODE, null);
	} catch (final CoreException exception) {
		final FailureReport failure = new FailureReport()
			.message("The run configuration “%s” cannot be launched!", this.launchConfiguration)
			.cause(exception)
			.recoverable()
			.retryWith(this::execute);
		FAILURE_HANDLER.handle(failure);
	}
}
```

This is not so much effort, is it?

In the moment, this will simply throw the exception for him. But unlike when throwing a `RuntimeException`, **this can be hanleded by the GUI in the future**!

A this point, the GUI could show a dialog like:

```
**Error!**

“Eclipse Run Configuration Launcher” reported an error:

The run configuration “Run all Tests” cannot be launched!

Details >> | Retry the action | Continue without the action | Abort the analysis
```

And now, `Details` will display all details provided by Eclipse, `Retry the action` will retry to run the configuration and `Continue without the action` will continue the analysis but without having run the failed configuration.

**Comment by jGleitz** [comment]
Any comments on this? From my point of view, using this API would not need much effort but allow us to better handle errors in the future.

If we decided about this soon, we could start using it for new code.

**Comment by RomanLangrehr** [comment]
I like the idea. I have no idea, how the retry should work (With Java reflections?!, Don't we need to save our current stack for that??), but the API is a good idea.

**Comment by jGleitz** [comment]
>  I have no idea, how the retry should work
> With Java reflections?!

No, no black magic needed for that! The retry logic is provided in a `Runnable` or `Supplier<T>` (best written as lambda, but you can also use an old school anonymous object).

Generally, retrying will mean calling a method again with the same parameters. But you have these parameters when the failure occurred, so usually, you’ll just provide a `Supplier` that will call the method with the same parameters again and return what it returns.

In the example above, this is done with ` .retryWith(this::execute)`

> Don't we need to save our current stack for that?

No, we don’t, because we’re never losing it. We are *not* throwing an exception, so the handler is *deeper* in the stack. The programmer needs to be aware that the failure handler might return having fixed the issue and react accordingly (e.g. not doing work that will already be done at this point).

So a usual pattern will be:

```java
public ReturnType myMethod(ParameterType1 param1, ParameterType2 param2) {
    // code
    if (failed) { 
        final FailureReport<ReturnType> failure = new FailureReport<ReturnType>()
            // set up the report
            .retryWith(() -> myMethod(param1, param2));
        return FAILURE_HANDLER.handle(failure);
    }
    // more code
}
```

Note that I just added support to return values from recover functions just now.

Did this explain the process?

**Comment by RomanLangrehr** [comment]
Yes, thanks.
Lgtm.

**Comment by jGleitz** [comment]
> Lgtm

Then this should be tested (it’s not much to do).

**Comment by RomanLangrehr** [comment]
@jGleitz  Can you please add your example

> 
```java
public void execute() {
	try {
		this.launchConfiguration.launch(ILaunchManager.RUN_MODE, null);
	} catch (final CoreException exception) {
		final FailureReport<Void> failure = new FailureReport<Void>()
			.message("The run configuration “%s” cannot be launched!", this.launchConfiguration)
			.cause(exception)
			.recoverable()
			.retryWith(this::execute);
		FAILURE_HANDLER.handle(failure);
	}
}
```

to the Javadoc?

**Comment by jGleitz** [comment]
Should we move this into it’s own package?

**Comment by RomanLangrehr** [comment]
I think that's a good idea.

**Comment by jGleitz** [comment]
Both done.

**Comment by jGleitz** [comment]
@viridispirus: How much is still missing for this to be finished?

**Comment by viridispirus** [comment]
There five methods i have still to test. The rest is tested so far.

**Comment by viridispirus** [comment]
#703
