### ISSUE TITLE
Write Beagle Controller (facade)

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#658]

**Comment by jGleitz** [comment]
I propose to add the package `de.uka.ipd.sdq.beagle.core.facade` for all facade related classes (like `UserConfiguration`, `BeagleController`, `BlackboardFactory` etc.). This would clearly communicate the API.

I also think `UserConfiguration` should be renamed to something like `FacadeConfiguration`. (Because it’s not GUI specific any more).

**Comment by m1cm1c** [comment]
> I also think `UserConfiguration` should be renamed to something like `FacadeConfiguration`. (Because it’s not GUI specific any more).

It doesn't read `GuiConfiguration` but `UserConfiguration` and it still is about what the user configured. Renaming it is a good idea, though. I don't like the term `UserConfiguration` but think that `FacadeConfiguration` describes it less well than `UserConfiguration`.

**Comment by jGleitz** [comment]
> Renaming it is a good idea, though.

Renaming is the more important part for me. (Getting `User` out of the name). I surely don’t insist on `FacadeConfiguration`.

As it’s the configuration that will be passed to the `BeagleController`, we could name it `BeagleConfiguration`.

**Comment by m1cm1c** [comment]
Agreed and done.

**Comment by jGleitz** [comment]
I pushed my proposal for a `BeagleConfiguration`, including a way to obtain source files, to `beagle-configuration` in our repositorty. I’d highly appreciate if you could have a look at it and tell me what you think about it. (Look at the package `de.uka.ipd.sdq.beagle.core.facade`).

**Comment by jGleitz** [comment]
[See the Javadoc](http://beagle-pse.github.io/Beagle/branches/beagle-configuration/javadoc/de/uka/ipd/sdq/beagle/core/facade/package-summary.html)

**Comment by m1cm1c** [comment]
You should describe what "finalised" means.

Why isn't it possible to read information if the class isn't in the "finalised" state? This makes it impossible to use it as a date object for a GUI which itself isn't a bad thing but we decided to call the data object of the GUI "BeagleConfiguration" and these classes now share the same name.

**Comment by jGleitz** [comment]
> You should describe what "finalised" means.

> The configuration has two states: A set up state, during which values may be modified but cannot be read, and a finalised state, in which it is immutable and can only be used to obtain values. The transition from the set up state to the finalised state is done through finalise(). The inverse transition is not possible. Trying to perform an action that is not allowed for the momentary state results in an IllegalStateException being thrown.

Taken from the Javadoc. Isn’t that enough?

> Why isn't it possible to read information if the class isn't in the "finalised" state?

It’s the easiest way to assure that the class is transitioned into *finalised*.

> This makes it impossible to use it as a date object for a GUI

Oh, that’s correct. So maybe it would be better to make `BeagleController` throw an `IllegalArgumentException` if the passed configuration isn’t *finalised*.

**Comment by jGleitz** [comment]
@m1cm1c: I removed the restriction

@RomanLangrehr: Please remember to throw the `IllegalArgumentException` in `BeagleController`, as detailed above.

**Comment by jGleitz** [comment]
>  but we decided to call the data object of the GUI "BeagleConfiguration" and these classes now share the same name.

Ideally, the `BeagleConfiguration` can be the data object of the GUI and the facade. Because the main task of the GUI is to collect all information needed by the facade. So it’d make sense to make the GUI use the facade’s configuration object.

**Comment by m1cm1c** [comment]
Oh, I didn't read the class Javadoc and expected the documentation of this at the member variable declaration of `finalised`. That's of course a very sufficient description.

> So maybe it would be better to make `BeagleController` throw an `IllegalArgumentException` if the passed configuration isn’t *finalised*.

Yes, that's better.

> @m1cm1c: I removed the restriction

Thank you.

**Comment by m1cm1c** [comment]
Is this ready for a PR?

**Comment by jGleitz** [comment]
> Is this ready for a PR?

If you mean the facade itself: Surely not.

If you mean the configuration: It still needs tests by @viridispirus

**Comment by m1cm1c** [comment]
I only meant the beagle configuration. I just talked to @viridispirus about him writing the tests for user configuration so we can get the GUI merged but I'd rather have him write tests for the beagle configuration.

**Comment by viridispirus** [comment]
This is still done, or not?

**Comment by RomanLangrehr** [comment]
Yes it is, just PR-it, see #711
