### ISSUE TITLE
Application Fields

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#66]
We now have several application fields and target groups. These have to be written out in full next.

*(This does __not__ mean it is not allowed to add one anymore)*

**Comment by acBerger** [comment]
We have "/A110/ As an optional feature, Beagle has the additional possibity to be run on a Server." in Operation Conditions. I am not sure if this belongs here.
Or maybe we should change it into "/OA100/" to point out it is optional (nice to have). If we do so we have to add "/OA#/" to "Reference notation".

**Comment by flyfl** [comment]
You're right. This was an optinal attribute for certain.

**Comment by acBerger** [comment]
1) Should we add a section /OA#/ or try to put this into another chapter, which already has such a section?
2) Even through I created a pull request ( #81 ) this is not finished yet.

**Comment by jGleitz** [comment]
The “Application” chapter is draft ready. This means:

 * It includes all essential content
 * It includes most optional content
 * It’s wording is understandable. (“good” wording will follow when working towards final!)

Please report any issues with the chapter in specific new issues.
