### ISSUE TITLE
Formatter vs. Checkstyle on Annotation Array Values

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#676]
![](http://i.imgur.com/OENgIRu.png)

**Comment by acBerger** [comment]
As I could not find a possiblity to 'teach' the formatter to have only one line for this. I try to adapt the checkstyle to accept the way the formatter does.

**Comment by acBerger** [comment]
Unfortunately I could not find a solution for this problem.

**Comment by acBerger** [comment]
I think this is something you should use @jGleitz's changes of #688 .

**Comment by jGleitz** [comment]
> I think this is something you should use @jGleitz's changes of #688 .

I think Checkstyle is right at this point, and the Formatter is wrong. So I guess putting the whole annotation in one line and wrapping it in `@formatter:off` and `@formatter:on` is the better solution here.

**Comment by acBerger** [comment]
Yes. You are right.

**Comment by acBerger** [comment]
As there is a solution for this: closed.
