### ISSUE TITLE
Missing blackboard things.

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#682]
We forogt during design some important things:
* At the beginning, some should add everthing as "to be measured" This could be done by:
 * The blackboard
 * The final judge (but doesn't makes sense, does it?)
 * The analysis controller (my favorite)
 * The measurement result analysers (bad idea)

* After the measurement, the toBeMeasured Elements should be cleared. I think the `MeasurementController` should do this after running *all* measurement tools.
The blackboard and the `MeasurementControllerBlackboardView` need a methode for this.

**Comment by RomanLangrehr** [comment]
By the way: The tests for the controllers won't work without this beeing fixed. So this should be done soon.

**Comment by jGleitz** [comment]
> The analysis controller (my favorite)

I agree.

**Comment by RomanLangrehr** [comment]
I take this as decided.
@m1cm1c  Please implement the changes in the controllers branch, because otherwise I can't write tests for them.

**Comment by m1cm1c** [comment]
The first point is done. However, I disagree that the seconds point should be done by the measurement controller. This should be done by the analysis controller as well.

We need methods for this on the blackboard, @viridispirus.

**Comment by viridispirus** [comment]
So we need on the blackboard methods which clear the toBeMeasured element lists?

**Comment by m1cm1c** [comment]
Yes.

**Comment by m1cm1c** [comment]
Or replace them by new ones.

**Comment by jGleitz** [comment]
>  However, I disagree that the seconds point should be done by the measurement controller.

I thought about that a little more. And I think you’re right.

**Comment by m1cm1c** [comment]
Done. It's  in the ip-130 feature branch.
