### ISSUE TITLE
Turn off code coverage

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#692]
Can we please turn of the code coverage checks in Travis?

1) We have the webiste  with the report, there we can check if the code coverage is okay manually.
2) There are too many situations, where 100% code coverage is not possible
 * The assertions in the measurement event parser
 * The Measurement Controller can't reach 100% code coverage, because one line is never executed because the ParameterChangeMeasurementResults are not yet parsed
 * The analysis controller has too loops that get never executed 0 times.

**Comment by acBerger** [comment]
If we turn it off we have to check the website, otherwise some methods could easily be forgotten. There was more than one case in which we only recognized missing tests because travis failed.

**Comment by RomanLangrehr** [comment]
But I think you forget it more likly, when you turn coverage off for half of the classes.

**Comment by jGleitz** [comment]
I still think that asserting code coverage is a very good idea. But I also see that jacoco’s shortcomings are a real problem. Assertions for example are a *good* thing. We should use them! Jacoco supports ignoring them, but the stupid gradle plugin doesn’t.

Maybe the following approach is a solution that keeps quality without holding us back:

 1. Show all classes in the coverage report on the website.
 2. *Always* post the website for every PR
 3. Pick an emoji Reviewable supports that conveys “test coverage okay”
 4. Pick an emoji Reviewable supports that conveys “test coverage not okay”
 5. Adapt the Reviewable code to require at least one emoji (as picked in 3) like we do it with the lgtms

This would force us to explicitly talk about test coverage for every PR. What do you think about that?

**Comment by RomanLangrehr** [comment]
I think that's a good idea.

**Comment by acBerger** [comment]
I agree.

**Comment by viridispirus** [comment]
I agree, too.

**Comment by acBerger** [comment]
I suggest :o: and :white_check_mark: for "test coverage not okay" and "test coverage okay".
If you do not like them check [this table] (http://www.emoji-cheat-sheet.com/) for others.

I am going to change the gradle code and remove the lable " //coverage: off" from all classes in master. Please make sure that none of the PRs contains these labels after my PR was merged.
@jGleitz is going to change the reviewable code when the other needed changes are merged.

**Comment by jGleitz** [comment]
The Reviewable code is installed. It can easily be adapted to use other emojis or produce other messages.

**Comment by acBerger** [comment]
Does anyone disagree with one of the suggested emoticons?

**Comment by viridispirus** [comment]
I am not.
Am 13.02.2016 13:02 schrieb "acBerger" <notifications@github.com>:
