### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by RomanLangrehr** [Beagle-PSE/Beagle#7]
In my opinion our project name "Beagle" is pretty bad, due to two reasons:

1. What the existing software called "Beagle" does, is not exactly what we will (probably) do in our project. At least Beagle focuses on the recognition of control and data flows while we will rather focus on measurement, will we?

2. Two software projects with a similar target and the same name will definitly lead to lots of confusion. We should avoid this!

Any suggestions on names for our project are welcome!

When we rename our project, we should rename our organziation, here on github, too.

**Comment by acBerger** [comment]
I agree. We should change the name.

**Comment by RomanLangrehr** [comment]
What about: PAREPCo (Performance Annotator for Reverse Engineered Palladio Components) or PAREPCoM (Performance Annotator for Reverse Engineered Palladio Component Models)?

**Comment by jGleitz** [comment]
> "Beagle" is pretty bad

There are reasons to change it, but I wouldn't call it "pretty bad".

>  At least Beagle focuses on the recognition of control and data flows

Yes… and no. Beagle does dynamic code analysis. We focus on resource demands, but ideally we'd contribute to the control flow information, too (as we'll probably find such information on the way)

> Two software projects with a similar target and the same name

For me, "Beagle" is a software invented in a dissertation. So there is only **one** software. There are two implementations of it, but the existing one will never be used again.

**Comment by jGleitz** [comment]
> PAREPCo, PAREPCoM

 1. I'd prefer something more memorable (but I don't have a better idea in the moment
 2. I don't think "performance" is the right term here. We annotate _resource demands_. They may be used to simulate performance. But performance itself includes a lot of other things, doesn't it?
  * performance describes a system or a component as a whole
  * performance depends a lot on deployment and usage, resource demands don't
  * performance includes some kind of rating, resource demands don't

**Comment by viridispirus** [comment]
How about DARD: Dynamic Analysis of Resource Demand

**Comment by jGleitz** [comment]
I like the name, but we a re not actually analyzing resource demands. We are analyzing software (to determine resource demands of its parts)

**Comment by RomanLangrehr** [comment]
I like the name, too.
Maybe "Dynamic Analysis for Resource Demands" is a good idea, as creating resource demands is the target of our software.

**Comment by m1cm1c** [comment]
Dynamic Inquiry of Resource Demand would solve the problem @jGleitz addressed, but Dird might not be the best name possible.

**Comment by flyfl** [comment]
DASC, Dynamic Analysis of Software Components. Would that fit better?
Because the parameterization is based on the structure of the components and their interfaces.
However, then we don't have anything about the resource demands in it.

**Comment by m1cm1c** [comment]
How about `Dynamic Resource Requirements Inquiry of Software Components` (`DyRRISC`)?

**Comment by viridispirus** [comment]
DyRRISC is a good name.

2015-11-19 0:33 GMT+01:00 m1cm1c <notifications@github.com>:

**Comment by jGleitz** [comment]
This has to be decided until Friday, 2015-11-19, 14:00

**Comment by RomanLangrehr** [comment]
> How about Dynamic Resource Requirements Inquiry of Software Components (DyRRISC)?

I like that name, too. Im just not sure, if <a href="http://dict.leo.org/ende/index_de.html#/search=Inquiry&searchLoc=0&resultOrder=basic&multiwordShowSingle=on"> Inquiry</a> is the correct word for that.

**Comment by acBerger** [comment]
I would prefer a name which I can pronounce and is easier to remember.
Altough I have to admit I have no better idea yet.

**Comment by m1cm1c** [comment]
We all tried to make acronyms (pronounceable abbreviations). You can pronounce `DyRRISC` (that's why I put the `y` in there).

**Comment by jGleitz** [comment]
> We all tried to make acronyms

Yes we did, because it’s easiest. I actually prefer names that have a deeper meaning (Like Palladio, [Protractor](https://angular.github.io/protractor/#/), and [grunt](http://gruntjs.com/)).

However, I don't have good one just right now. I’ll try to come up with one.

**Comment by jGleitz** [comment]
If we stick to acronyms: **DACS** (**D**ynamic **A**nalysis of **C**omponent based **S**oftware)
would be easier to remember and still fit if the project evolves to doing more than analysing resource demands.

**Comment by flyfl** [comment]
@jGleitz That is nearly what I proposed (~DASC), that is why I don't have objections. But I totally agree with the idea that our name should be easy to remember. (`DyRRISC`  is quite bulky in my opinion)

**Comment by jGleitz** [comment]
We’ll have to decide very soon

Are there any more proposals?

If not, could everybody please clearly state their favourite?

Mine is Beagle.

**Comment by RomanLangrehr** [comment]
My favorites are DyRRISC and DACS. If I have to decide between them, I would prefer DACS.

**Comment by viridispirus** [comment]
I prefer DACS.

2015-11-20 11:43 GMT+01:00 Roman Langrehr <notifications@github.com>:

**Comment by m1cm1c** [comment]
I prefer DyRRISC.

**Comment by acBerger** [comment]
I prefer DACS, Beagle would be okay.

2015-11-20 12:54 GMT+01:00 m1cm1c <notifications@github.com>:

**Comment by jGleitz** [comment]
As @flyfl already stated, he is okay with _DACS_, to.

So we decide for DACS, with 4 votes in favour.
