### ISSUE TITLE
Re-define "branch construct" and "loop construct"

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#71]
The definition of above terms is technically correct, but not quite what we’ll need.

We will never analyse _every_ `if` and `while`, but only those that affect the `SEFF`, e.g. those that change the calls to other components a component does.

I’d like to adapt our definitions to only apply for those case, this would make writing easier.

Does everybody agree with that?

**Comment by RomanLangrehr** [comment]
Yes, that sounds like a good idea.
