### ISSUE TITLE
Realise the GUI as Eclipse Launch Configuration

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#717]

**Comment by jGleitz** [comment]
Article on the topic: https://eclipse.org/articles/Article-Launch-Framework/launch.html

**Comment by RomanLangrehr** [comment]
[The article](https://eclipse.org/articles/Article-Launch-Framework/launch.html) recommends in chapter "Separating model and UI" to put the LaunchConfiguration and the GUI thinkgs for this launch configuration in two different plugins.

Should we put our Launch Configuration in "Beagle Core" and the GUI thinks for the Launch Configuration in "Beagle GUI"?
