### ISSUE TITLE
Simple Tests

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#745]
Unit tests for these simple classes have to be created:

- [x] `ProjectInformation`
- [x] `BlackboardCreator`
- [ ] `MeasurementResultAnalyserAverage`
- [x] `MeasurementResultAnalyserBlackboardView`
- [x] `ProposedExpressionAnalyserBlackboardView`

**Comment by viridispirus** [comment]
I check the finished tesets but have not pushed yet because some problems with smartGIT. It still works on my machine.

**Comment by m1cm1c** [comment]
Update: The problems are resolved. See #764.

**Comment by jGleitz** [comment]
Fixed by #764
