### ISSUE TITLE
Thread Communication

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#758]
For some of the features we want to implement in this phase, namely PAUSE, ABORT and TIMEOUT, we need some sort of thread communication.

I see several questions when implementing this, which I want to discuss here.

 1. From my pov, there are two concepts to realise this:
  1. Thread interrupts: The running thread is sent an interrupt to signal he’s supposed to stop what he’s doing
   1. using asynchronous callbacks: The running thread can register for the events and provide a method that handles them (could also be realised through the analyser interface, thus inforcing implementation of the handlers).
 1. For either concepts, we need more threads than we have right now. Who spawns them? I see two possibilities:
    1. spawn contributor threads: The analysis controller spawns a new thread to execute a contributor
    1. spawn event management threads: The instances issuing the events are in a separate thread (like one thread for the TIMEOUT, one thread for the GUI (that issues PAUSE and ABORT))
 1. If we use interrupts, does the interrupted thread get information about *why* it was interrupted (e.g. to save data for pause but stop immediately for abort)? If yes, how does it get it?

I’d like to hear your thoughts about this. I think 1.i and 2.ii is the best suited combination for the issue, but that raises question 3.

**Comment by RomanLangrehr** [comment]
How do you want to send an "interupt signal" to a thread?

**Comment by jGleitz** [comment]
Using [Thread#interrupt](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#interrupt--). (That’s what will cause an `InterruptedException` to be thrown if the Thread is sleeping).

See also the [Java Tutorial on Interrupts](https://docs.oracle.com/javase/tutorial/essential/concurrency/interrupt.html).

**Comment by RomanLangrehr** [comment]
But our therads are running! You can't "interrupt" them!

**Comment by jGleitz** [comment]
> But our therads are running! You can't "interrupt" them!

Why not? As I detailed above, I need to be in another thread to do so. Now if I do, there are two possibilites:

 * The Thread is sleeping (because of `wait`, `join` or `sleep). I can thus handle the interrupt by catching the (checked !) `InterruptedException`. This will be the case if the contributor uses worker threads (which the for example is done when instrumenting, but will also likely be done by the genetic analyser).
 * The Thread is working. Thus, it’s interrupted status is set. The Thread can then read that flag at certain checkpoints at which he is prepared to handle the interrupt. If he doesn’t read the flag at all, he will not notice the interrupt.

**Comment by RomanLangrehr** [comment]
>  * The Thread is sleeping (because of `wait`, `join` or `sleep`). It can thus handle the interrupt by catching the (checked !) `InterruptedException`. This will be the case if the contributor uses worker threads (which for example is done when instrumenting, but will also likely be done by the genetic analyser).

And how are the worker threads paused/aborted?

**Comment by jGleitz** [comment]
> And how are the worker threads paused/aborted?

There is no automatic mechanism for that (how could there reasonably be one?). The master thread is woken up and it must handle the situation (it could kill the threads, it could wait for them and then exit, it could simply ignore the interrupt and go to sleep again, or whatever suitable).

**Comment by jGleitz** [comment]
How’s progress on this?
