### ISSUE TITLE
[Checkstyle] Anonymous Inner Class Length

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#762]
Anyone in favor of getting rid of this?

![](http://i.imgur.com/nYRYMud.png)

**Comment by jGleitz** [comment]
I’m not. I think this nesting makes the code unnecessarily hard to read. I think something like `


```java
public ConstantTimeout() {
    // initialisation
    new Thread(this::notifyOnReached).start();
}

private void notifyOnReached() {
    // logic of the Runnable
}
```

is a lot easier to read. For instance, I can understand what the constructor does without having to read the code inside the runnable, because the method has a speaking name.

**Comment by m1cm1c** [comment]
Okay. Done.
