### ISSUE TITLE
Correct Mistakes in Purpose (Chap. 1)

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#77]
I reread our SRS and found following mistakes:

- /C20/: *Beagle shall automatically annotate its resource demand findings in a given
instance of the software’s PCM instance.*
the sentence contains the word "instance" twice, I think one has to be removed.

- /OC30/: it should be "approximately" instead of "aproximatly"

- 1.3. Maybe we should add a reason to some of the boundarys. e.g. */B10/ Beagle does not perform actual measurements on source code*   as this is done by ...

**Comment by jGleitz** [comment]
you’re right. Can you create a PR for this?

**Comment by acBerger** [comment]
What's about 1.3? Do we want to have a more detailed description of our boundarys or the reasons for them.

**Comment by jGleitz** [comment]
Yeah, I think that’s good style. We already sometime do this at other point and I think it helps us to transport our image of our software.
