### ISSUE TITLE
Look into LaTeX Warnings

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#79]
Rendering the SRS throws an unsettling amount of warnings. They need to be investigated. Warnings we can do nothing about may be muted. The rest should be fixed.

**Comment by RomanLangrehr** [comment]
In the first and maybe the second run latex usually throws many warning which indicate, that LaTeX should be run again.
So we should only care about the warnings in the last run.

**Comment by jGleitz** [comment]
I think this was fixed by #211.
