### ISSUE TITLE
Glossary Entry for `Palladio Component Model` Not Shown

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#80]

**Comment by jGleitz** [comment]
This is likely the same bug like the one we just noticed in #75.

**Comment by acBerger** [comment]
No, I don't think so. First, at least in my local pdf there is the entry (it's empty but it's there). And second, I am pretty sure "PCM" is used in the document.
For example in the introduction of "Purpose" and in the chapter "Functionality"

**Comment by jGleitz** [comment]
Well, this can be fixed by using `\gls` in the PCM definition. #73 includes that.
