### ISSUE TITLE
Illegal State Exception in Beagle Controller

### ISSUE THREAD

**Issue by viridispirus** [Beagle-PSE/Beagle#811]
When Beagle is running a `IllegalStateException` is thrown by click the pause button.

Here is the detailed error message:

![illegalstateexception](https://cloud.githubusercontent.com/assets/10431811/13724932/fedc75ea-e894-11e5-8a66-f394c5d1afae.PNG)

Please @m1cm1c have a look after it.

**Comment by jGleitz** [comment]
I want to add that at the point the button is clicked, the analysis definitely started (the run configuration executing the test project was already launched).

**Comment by m1cm1c** [comment]
Solved.
