### ISSUE TITLE
Context Menu is Broken!

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#815]
Right clicking on a `.repository` file and selecting “Analyse with Beagle” freezes Eclipse and has no other effect.

**Comment by RomanLangrehr** [comment]
I can't reproduce this. Which branch did you use?

**Comment by jGleitz** [comment]
> Which branch did you use?

`master`

**Comment by RomanLangrehr** [comment]
On my machine everything works.

**Comment by jGleitz** [comment]
This seems to be specific to my new GUI (#796). Eclipse didn’t reload properly after switching branches.

**Comment by jGleitz** [comment]
I fixed it there.
