### ISSUE TITLE
Challenges

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#86]
As discussed today (2015-11-23), we’ll introduce a chapter called “Challenges”. Some of the points can be taken from today’s meeting minutes.

**Comment by RomanLangrehr** [comment]
@/C130/
>I don't think so, we could test it like this:
Component A is started at time t0
Component B starts Component A at time t1
Component B returns at time t2
Component A returns at time t3
Then Component B needs time t2-t1 and Component A needs time t3+t1-t2-t0.
On the other hand, this isn't always an option: When A calls B in loop a hundred times, we would measure B a hunderd more times than A.

Joshuas reply:
> I think that most of the times, things will be even easier than that, as we’ll simply ignore calls to components not under test.

**Comment by RomanLangrehr** [comment]
@/C110/
> of Beagle? Then I would rather put this to /Q#/ and make it more precise (like: Beagle should be able to analyse a Desktop application on an average Desktop PC...)

**Comment by jGleitz** [comment]
@/C130/

There might, however, still be a need to mock components. That may be the case if:
 * Required software components aren’t provided (do we even support that? We’ll need to add a requirement for it!)
 * Requested components don’t return in time (e.g. because they wait for user input)
 * We want to decrease testing time

It’s likely Kieker already offers solutions for this. That’s why it’s in “challenges” – we’ll clearly need to investigate.

**Comment by m1cm1c** [comment]
@/C130/ @RomanLangrehr After reading what @jGleitz said, what do you think?

**Comment by m1cm1c** [comment]
@/C110/ No. I'll clarify this in a few minutes. Thanks for the hint.

**Comment by RomanLangrehr** [comment]
@/C130/ I agree with @jGleitz .

**Comment by jGleitz** [comment]
Does anybody have something to add to this chapter after #146 before it can be considered *draft ready*? This means:

 * It includes **all** essential content
 * It includes **most** optional content
 * It’s wording is **understandable**. (“good” wording will follow when working towards final!)

@m1cm1c, please report as you’re currently assigned.

**Comment by acBerger** [comment]
As it seems that no one has something to add or change here, I'm going to close this.
