### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#88]
Scenarios for our use cases need to be created where they make sense.

**Comment by jGleitz** [comment]
I think a scenario capturing `/A20/`, `/A30/` and maybe even `/A40` might be nice, too. What do you think?

**Comment by flyfl** [comment]
Totally agreed. One more scenario should be at least added.

**Comment by acBerger** [comment]
If we still want to have another scenario someone has to write it.
