### ISSUE TITLE
Data Part

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#89]
The SRS should contain a part defining the data Beagle takes and produces. Chapter 4 and 5 should then reference this part.

**Comment by jGleitz** [comment]
Does anybody have something to add to this part after #142 before it can be considered *draft ready*? This means:

 * It includes **all** essential content
 * It includes **most** optional content
 * It’s wording is **understandable**. (“good” wording will follow when working towards final!)

**Comment by acBerger** [comment]
I have nothing to add and the wording is understandable.
For me it is draft ready.

**Comment by acBerger** [comment]
As it seems that no one has something to add or change here, I'm going to close this.
