### ISSUE TITLE
Software Requirements Specification Document Format

### ISSUE THREAD

**Issue by jGleitz** [Beagle-PSE/Beagle#9]
We have to decide on a document format for the software requirements specification.

Are we obliged to use a certain format (like the one presented in the software engineering lecture)?

I kind of dislike the draft given in the lecture, as it (from my point of view) does not clearly state what exactly is to be included in each section.

There is an [IEEE standard](https://en.wikipedia.org/wiki/Software_requirements_specification) for software requirement specification, unfortunately, we only get access to the outdated version from 1998, not the most recent one from 2011, with our university accounts.

There is another recommendation in [Lehrbuch der Software-Technik: Basis-Konzepte und Requirements-Engineering](http://link.springer.com/book/10.1007/978-3-8274-2247-7) (pp. 492), which we all can access for free. Although we'll have to translate it, it might be easiest to adopt that.

**Comment by jGleitz** [comment]
The book's recommendation is partially based on the IEEE standard from 1998.

**Comment by m1cm1c** [comment]
How do you get access to the book / the chapter?

**Comment by jGleitz** [comment]
Use the link I provided, click on "Get Access", click on "Log in to your account" on the next page, select "Log in via Shibboleth or Athens"  on the next page, choose the KIT in the second select box on the next page (I used "Karlsruher Institut f.  Technologie Forschungszentrum GmbH") and hit " Log in via Shibboleth". Use your u-account to log in. 
You will not be led back to the initial page, so use the provided link again. This time, the big Button reads "Download Book (PDF, 4085 KB)". Hit it, and there you are.

**Comment by m1cm1c** [comment]
Thank you, it worked. Note for others: You might have to log in before clicking onto "Get Access".

> I kind of dislike the draft given in the lecture, as it (from my point of view) does not clearly state what exactly is to be included in each section.

Ack.

In the book, I can't find anything nearly as detailed as [what can be found on Wikipedia](https://en.wikipedia.org/wiki/Software_requirements_specification). In fact, I scrolled about 100 pages through the ebook before realizing that there won't be a big itemization like on Wikipedia and the section starting at 492 already ands with page 496.

The example organization found on Wikipedia, however, seems ample regarding structure and level of detail and adequate for a 40 page software requirements specification, so I suggest we use it.

**Comment by flyfl** [comment]
I don't think that we should disregard the document format presented in the SWT lecture. In my opinion it states very well what's to be done in which section and I am more used to it. Maybe we can use this format as a basis, that is modified or extended in a way that everyone can cope with it?

**Comment by jGleitz** [comment]
> In the book, I can't find anything nearly as detailed as what can be found on Wikipedia

Did you reference the right wikpedia article? Because the one you referenced (IEEE) gives a bullet point list, but no details at all.

Let me give you an example:

For the introduction, wikipedia states:
 > * Introduction
      * Purpose
      * Definitions
      * System overview
      * References

No more details are given. And I’m not sure what the exact scope of “System overview” is. Thinking about it, I’m not even sure what to write there at all.

I have now realised that the book is not as detailed as I thought. The detailed section I Iiked is about the V model XT (pp 487).
Nonetheless, find the instructions given on page 493 extremely valuable. And I have the feeling I understand better what to put where.

Is there another, better source?

**Comment by jGleitz** [comment]
Another point:

The article does not define how to write down each of the points. Bullet points? Continous text? Enumeration?

The book states that.

**Comment by jGleitz** [comment]
@flyfl: Maybe you’re right. I hate how the lecture mainly uses examples instead of giving proper definitions. But nevertheless it might be the best source we have.

**Comment by m1cm1c** [comment]
Yes, Wikipedia only mentions everything but doesn't talk about it in any detail whatsoever. But the book talks about almost nothing either and doesn't provide a list of what to write in there.

So here is what Wikipedia mentions:

    Introduction
        Purpose
        Definitions
        System overview
        References
    Overall description
        Product perspective
            System Interfaces
            User Interfaces
            Hardware interfaces
            Software interfaces
            Communication Interfaces
            Memory Constraints
            Operations
            Site Adaptation Requirements
        Product functions
        User characteristics
        Constraints, assumptions and dependencies
    Specific requirements
        External interface requirements
        Functional requirements
        Performance requirements
        Design constraints
            Standards Compliance
        Logical database requirement
        Software System attributes
            Reliability
            Availability
            Security
            Maintainability
            Portability
        Other requirements

And here is a combined one with everything the book mentions being marked with `#` and everything the book mentions but Wikipedia doesn't marked with `!`:

    Introduction
        # Purpose
       !# Circumstances
        Definitions // includes glossary
        # System overview
        References
    Overall description
        Product perspective
            System Interfaces
            User Interfaces
            Hardware interfaces
            Software interfaces
            Communication Interfaces
            Memory Constraints
            Operations
            Site Adaptation Requirements
        Product functions
        User characteristics
        Constraints, assumptions and dependencies // includes acceptance criteria and sub-system structure
    Specific requirements
        External interface requirements
        # Functional requirements
        Performance requirements
        Design constraints
            Standards Compliance
        Logical database requirement
        Software System attributes     // includes quality requirements
            Reliability
            Availability
            Security
            Maintainability
            Portability
        Other requirements

As you can see, there is a lot of stuff the book doesn't mention at all. Maybe we can use the list from Wikipedia combined with the details the book provides. By incorporating `Circumstances` into the list Wikipedia provides, we'd still use everything in the chapter of the book.

> And I’m not sure what the exact scope of “System overview” is. Thinking about it, I’m not even sure what to write there at all.

That's point 3 ("Kontext und Überblick") in the book. It writes
> Festlegung der relevanten Systemumgebung (Kontext) und Überblick
über das System:
> /K10/ Kontext 1 des Systems usw.

regarding it. That's it.

**Comment by jGleitz** [comment]
@m1cm1c I see your point. Can you agree on using the lecture, like @flyfl propsed?

**Comment by m1cm1c** [comment]
The lecture provides better structure than the book but it doesn't say anything about splitting the non-functional requirements into separate categories which would outline them nicely. Mixing reliability, availability, security, maintainability, and portability together, is just chaos. Furthermore, the lecture doesn't decide what exactly is to be included in non-functional requirements and in the examples there are non-functional requirements which just are descriptions of the user interface and user experience (which is unavoidable when using such a broad term).

However, some of the system models given in the lecture don't appear in the structure from Wikipedia. We should incorporate them and – of course – use the details provided by the lecture.

Regarding the points which appear in the book as well as in the lecture: Is there anything incompatible except for the lecture using very broad terms?

**Comment by jGleitz** [comment]
I think the lecture’s structure is widely compatible to the book’s (and vice versa).

So let’s use the lecture’s version and enhance it with the book’s recommendations, shall we?

**Comment by m1cm1c** [comment]
Why don't you want use the more fine-grained structure stated above?

**Comment by jGleitz** [comment]
> Why don't you want use the more fine-grained structure stated above?

It’s incompatible to both the book and lecture. And I think having more top level points and fewer nesting (which is the case in the lecture) is a lot better.

**Comment by jGleitz** [comment]
Plus, I don’t think your markers are correct, as the book elaborates on some points in other sections. The lecture handles most points more detailed (and ordered), too.

Last, I don't think we need a **such** fine grained structure (there are some points that don’t make sense in our context, too, which will not be missed).

**Comment by m1cm1c** [comment]
Nesting and itemizing gives clear rules of what to write and later find where. The book and lecture mix categories which should be separated together and the lecture even is inconsistent with what to put in which broad category. Apart from where the lecture is inconsistent with itself, where do you see an incompatibility?

Most of the items are useful even if they seem to be obvious. For example "Standards Compliance": We know which standards we have to comply with in order to make the software work together with existing software. But it should be documented somewhere. Neither the lecture nor the book specify where this should be done.

**Comment by jGleitz** [comment]
This has to be decided until Thursday, 2015-11-19, 18:00

**Comment by RomanLangrehr** [comment]
> Last, I don't think we need a such fine grained structure (there are some points that don’t make sense in our context, too, which will not be missed).

I totaly agree on that.

In <a href="https://pp.info.uni-karlsruhe.de/lehre/WS201415/pse_lambda/tipps.pdf"> tips for PSE </a>, Section 5 they say, we should use the structure of the SWT1 lecture, but we can make adaptions.

I think the structure of the book, as it is pretty similar to the one from the SWT1 lecture, is compliant with this, but the IEEE standard is not, as it has completly different structure.

In the IEEE structure, there are a lot of points, where I have no idea, what we should write there, e.g. "Memory Constraints". Some other points make no sense in our project, like "Logical database requirement" or "Portability". And there are points that are in conflict with the PSE strucutre, like "Design constraints". Design is our second topic.

Last but not least, everybody in our team is familiar with the lectures structure, so we will have less problems in deciding, which point goes where.


>Most of the items are useful even if they seem to be obvious. For example "Standards Compliance": We know which standards we have to comply with in order to make the software work together with existing software. But it should be documented somewhere. Neither the lecture nor the book specify where this should be done.

I think, that is a non-functional requirement.


> [The lecture] doesn't say anything about splitting the non-functional requirements into separate categories which would outline them nicely. Mixing reliability, availability, security, maintainability, and portability together, is just chaos. 

The lecture's strucutre dosn't mix these points. They just don't tell you how to structure your subsections in functional requirements, product data, and non-functional requirements, because this is project specific. When you look in the example Software Requirements Specification Document (Chapter 2.4 transparency 8ff), there is a project specific structure in subsections.

**Comment by jGleitz** [comment]
As I really need to start structuring and most people seem to agree on using the lecture structure, I will use this one.

I will use the [Pflichtenheft Handyverträge](https://ilias.studium.kit.edu/ilias.php?ref_id=435203&cmd=sendfile&cmdClass=ilrepositorygui&cmdNode=ed&baseClass=ilRepositoryGUI) of the lecture as a starting point.

I totally agree with @flyfl and @m1cm1c to modify and improve the structure based on the book and the Wikipedia article. Please post modifications you can already name in #10!
