### ISSUE TITLE
Marking of Quotes

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#91]
Quotes aren't visible at all. They currently look like a glitch in the document. I'd like them to either:
  * have a different font
  * have a different background
  * be in quotation marks

What do you prefer?

**Comment by RomanLangrehr** [comment]
In my opinion:

 * indirect citations should not be marked at all (except the \cite{...} somewhere)
 * Word by word citations should be in quotation marks
 * Word by word citations, that are prettly long (multiple lines) should be in qutation marks and get a seperate paragraph, which is indented in every line.

**Comment by jGleitz** [comment]
I totally agree with @RomanLangrehr. I’m strongly against using a different font.

So when citing, just put you stuff in quotation marks. When citing long, like @RomanLangrehr said, use `\quote` or `\quotation` (and of course put it in quotes)

**Comment by m1cm1c** [comment]
We could color the background gray like quotes on GitHub.

**Comment by jGleitz** [comment]
> We could color the background gray like quotes on GitHub.

That sounds like horrible typography to me.

**Comment by jGleitz** [comment]
(and please not that quotes on GitHub do not have a background)

**Comment by m1cm1c** [comment]
Oops, but some other websites do it.

GitHub uses gray font color which is a great way of indicating a quote, too.

**Comment by jGleitz** [comment]
I’ll close it as we found a solution. Typography details will be discussed at a later point.
