### ISSUE TITLE
Starting with upper case letter in lists

### ISSUE THREAD

**Issue by acBerger** [Beagle-PSE/Beagle#94]
I think we agreed on starting lists with an upper case letter in SRS.
Then we have to change this for "reference notation", as each points starts with a small letter there.
I can do this, when I add "/OT#/" for test cases for optional requirements, if you want.

**Comment by m1cm1c** [comment]
Imo it looks better the way it currently is.

**Comment by acBerger** [comment]
We have to stick to a standard, so either all starting with an upper case letter or all with a small letter.
 @m1cm1c: You want to have small letters, don't you?

**Comment by jGleitz** [comment]
The decision was: “start with a capital letter if it’s a full sentence”. The reference notation list do not form full sentences, so lowercase is okay there.

Rule of thumb: If you put a full stop in the end, capitalise the the first letter.

**Comment by acBerger** [comment]
okay.
