### ISSUE TITLE
Wrong Hyphenation

### ISSUE THREAD

**Issue by m1cm1c** [Beagle-PSE/Beagle#95]
"development" is divided as "devel – opment".

**Comment by acBerger** [comment]
"analysis" (or another word with this root) is divided as "anal - ysis". I do not think this is right either.

**Comment by m1cm1c** [comment]
@jGleitz http://www.dict.cc/?s=silbentrennung&=DEEN&= ;-) But it doesn't matter anyway.

**Comment by RomanLangrehr** [comment]
Analysed is divided correctly. [See here](http://www.hyphenation24.com/word/analysed/) or [here](http://www.thefreedictionary.com/analysis)
Development is divided correctly. [See here](http://www.hyphenation24.com/word/development/) or [here](http://www.thefreedictionary.com/development)

**Comment by jGleitz** [comment]
Englishmen are strange people.
